// Code generated by '_gen'

package gameboy

func (gb *GameBoy) renderTilesDMG() {

	var (
		scrollY  = gb.MemoryBus.IO[0x42]
		scrollX  = gb.MemoryBus.IO[0x43]
		windowY  = gb.MemoryBus.IO[0x4A]
		windowX  = int(gb.MemoryBus.IO[0x4B]) - 7
		lcdc     = gb.MemoryBus.IO[LCDC]
		scanline = (gb.MemoryBus.IO[LY])

		signedTiles      = !((lcdc>>4)&1 != 0)
		scanLineInWindow = windowY <= scanline
		winEnabled       = (lcdc>>5)&1 != 0
		useWindow        = winEnabled && scanLineInWindow
	)

	tileData := uint16(0x8000)
	if signedTiles {
		tileData = 0x8800
	}

	winMemory := uint16(0x9800)
	if winAddr := (lcdc>>6)&1 != 0; winAddr {
		winMemory = 0x9C00
	}

	bgMemory := uint16(0x9800)
	if bgAddr := (lcdc>>3)&1 != 0; bgAddr {
		bgMemory = 0x9C00
	}

	// yPos is used to calc which of 32 v-lines the current scanline is drawing
	var yPos uint8
	if useWindow {
		yPos = uint8((scanline - windowY))
	} else {
		yPos = uint8((scrollY + scanline))
	}

	var (
		// which of the 8 vertical pixels of the current tile is the scanline on?
		tileRow = uint16(yPos/8) * 32

		lastTileCol            = uint16(0xFFFF)
		data1, data2, colorBit uint8
	)

	for pixel := range width {

		var xPos uint8
		if winSpace := useWindow && pixel >= windowX; winSpace {
			xPos = uint8((int(pixel) - windowX))
		} else {
			xPos = (uint8(pixel) + scrollX)
		}

		// Which of the 32 horizontal tiles does this x_pox fall within?
		if tileCol := uint16(xPos / 8); tileCol != lastTileCol {
			lastTileCol = tileCol

			// PER PIXEL OF SCAN LINE, NEED TO CHECK IF PIXEL >= WX AS WELL TO CHOOSE TILE ADDR (BG VS WIN)
			tileAddress := bgMemory + tileRow + tileCol
			if useWindow && pixel >= windowX {
				tileAddress = winMemory + tileRow + tileCol
			}

			tileLocation := tileData
			if !signedTiles {
				tileNum := int16(gb.MemoryBus.VRAM[tileAddress-0x8000])
				tileLocation = tileLocation + uint16(tileNum*16)
			} else {
				tileNum := int16(int8(gb.MemoryBus.VRAM[tileAddress-0x8000]))
				tileLocation = uint16(int32(tileLocation) + int32((tileNum+128)*16))
			}

			bankOffset := uint16(0x8000)

			line := (yPos & 7)

			addr := tileLocation + uint16(line<<1) - bankOffset
			data1 = gb.MemoryBus.VRAM[addr+0]
			data2 = gb.MemoryBus.VRAM[addr+1]

		}

		colorBit = 7 - (xPos & 7)

		//colorNum := getVal(data2, uint8(colorBit))
		//colorNum <<= 1
		//colorNum |= getVal(data1, uint8(colorBit))
		colorNum := getColorVal(data2, data1, colorBit, colorBit)
		gb.pixelDrawn[pixel] = colorNum != 0

		if draw := !gb.bgPriority[pixel][scanline]; draw {
			gb.Screen[pixel][scanline] = gb.UnpackedMonoPals[0][colorNum]
		}

	}
}

func (gb *GameBoy) renderSpritesDMG(scanline int32) {

	lcdc := gb.MemoryBus.IO[LCDC]

	var ySize int32 = 8
	if (lcdc>>2)&1 != 0 {
		ySize = 16
	}

	gb.spMinx = [width]int32{}
	var lineSprites = 0
	for sprite := range uint16(40) {
		index := sprite * 4

		yP := gb.MemoryBus.OAM[index]
		yPos := int32(yP) - 16

		if scanline < yPos || scanline >= (yPos+ySize) {
			continue
		}

		// Only 10 sprites are allowed to be displayed on each line
		if lineSprites >= 10 {
			break
		}
		lineSprites++

		xP := gb.MemoryBus.OAM[index+1]
		xPos := int32(xP) - 8
		tileLocation := gb.MemoryBus.OAM[index+2]
		attributes := gb.MemoryBus.OAM[index+3]

		yFlip := (attributes>>6)&1 != 0
		xFlip := (attributes>>5)&1 != 0
		priority := !((attributes>>7)&1 != 0)

		// Set the line to draw based on if the sprite is flipped on the y
		line := scanline - yPos
		if yFlip {
			line = ySize - line - 1
		}

		dataAddress := (uint16(tileLocation) * 0x10) + uint16(line*2)

		data1 := gb.MemoryBus.VRAM[dataAddress]
		data2 := gb.MemoryBus.VRAM[dataAddress+1]

		for tilePixel := range uint8(8) {
			pixel := int16(xPos) + 7 - int16(tilePixel)
			if pixel < 0 || pixel >= width {
				continue
			}

			if gb.spMinx[pixel] != 0 && (gb.spMinx[pixel] <= int32(xPos)+SpritePriorityOffset) {
				continue
			}

			colorBit := tilePixel
			if xFlip {
				colorBit = byte(int8(colorBit-7) * -1)
			}

			//colorNum := getVal(data2, uint8(colorBit))
			//colorNum <<= 1
			//colorNum |= getVal(data1, uint8(colorBit))
			colorNum := getColorVal(data2, data1, colorBit, colorBit)

			if transparent := colorNum == 0; transparent {
				continue
			}

			drawPixel := (priority && !gb.bgPriority[pixel][scanline]) || !gb.pixelDrawn[pixel]
			if drawPixel {

				pal := UNPACKED_OBJ0
				if (attributes>>4)&1 != 0 {
					pal = UNPACKED_OBJ1
				}

				gb.Screen[pixel][scanline] = gb.UnpackedMonoPals[pal][colorNum]

			}

			gb.spMinx[pixel] = int32(xPos) + SpritePriorityOffset
		}
	}
}
