[main]
open     = "open a rom"
settings = "settings"
quit     = "quit"
dialog_title = "Open"
dialog_desc = "Roms (*.gb, *.gbc, *.gba, *.nds)"

[pause]

resume   = "resume"
settings = "settings"
main     = "main menu"

[toast]

saved = "saved"
muted = "muted"
unmuted = "unmuted"
controller_connected = "controller connected"
controller_disconnected = "controller disconnected"

[settings]

[settings.sidebar]
general = "general"
ui      = "ui"
gb      = "gb"
gba     = "gba"
nds     = "nds"
about   = "about"
return  = "return"

[settings.general]

general         = "general"
muted           = "muted"
show_fps        = "show fps"
init_fullscreen = "init fullscreen"
target_fps      = "target fps"
vsync_enabled   = "vsync enabled"
disable_saves   = "disable saves"
integer_scaling_desc = "a ratio of zero is dynamic"
integer_scaling = "integer scaling"
integer_scaling_ratio = "integer scaling ratio"
sample_rate_desc = "sample rate requires restart"
sample_rate = "sample rate"

keyboard        = "keyboard"
controller      = "controller"

select          = "select"
return          = "return"
mute            = "mute"
pause           = "pause"
left            = "left"
right           = "right"
up              = "up"
down            = "down"
fullscreen      = "fullscreen"
quit            = "quit"

save = "save"

[settings.ui]

ui              = "ui"
language        = "language"
languages       = ["english", "spanish"]
backdrop        = "backdrop"
bg_color        = "bg color"
fg_color        = "fg color"
accent_color    = "accent color"
apply_theme     = "apply theme"
ui_backdrop     = "ui backdrop"
ui_bg_color     = "ui bg color"
ui_fg_color     = "ui fg color"
ui_accent_color = "ui accent color"
save            = "save"

alphabet = [
    "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M",
    "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z",
    "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m",
    "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z",
    "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", ",", " ",
]

[settings.gb]

general = "general"
system        = "system"
systems        = ["auto", "dmg", "gbc"]
dmg_palette   = "dmg palette"
lightest      = "lightest"
light         = "light"
dark          = "dark"
darkest       = "darkest"
dmg_lightest  = "dmg lightest"
dmg_light     = "dmg light"
dmg_dark      = "dmg dark"
dmg_darkest   = "dmg darkest"
apply_palette = "apply palette"

bios = "bios"
dmg_bios_path = "dmg bios path"
gbc_bios_path = "gbc bios path"
direct_boot = "direct boot"

keyboard = "keyboard"
controller = "controller"

a      = "a"
b      = "b"
select = "select"
start  = "start"
left   = "left"
right  = "right"
up     = "up"
down   = "down"

save = "save"

[settings.gba]

general = "general"
optimize_idle_loops = "optimize idle loops"
rotation = "rotation"
rotations = ["0", "90", "180", "270"]

hardware = "hardware"
backup_type = "backup type"
backup_types = ["auto", "none", "eeprom", "sram", "flash", "flash128"]
force_rtc = "force rtc"
force_solar_sensor = "force solar sensor"
solar_sensor_level = "solar level"

bios = "bios"
bios_path = "bios path"
direct_boot = "direct boot"

keyboard = "keyboard"
controller = "controller"

a      = "a"
b      = "b"
select = "select"
start  = "start"
left   = "left"
right  = "right"
up     = "up"
down   = "down"
l      = "l"
r      = "r"
solar_minimum = "solar minimum"
solar_1 = "solar 25%"
solar_2 = "solar 50%"
solar_3 = "solar 75%"
solar_maximum = "solar maximum"
rotation_toggle = "rotation toggle"

save = "save"

[settings.nds]

screen = "screen"
layout = "layout"
sizing = "sizing"
rotation = "rotation"

layouts = ["vertical", "horizontal", "hybrid"]
sizings = ["even", "only top", "only bottom"]
rotations = ["0", "90", "180", "270"]

rtc = "rtc"
additional_hours = "additional hours"

bios = "bios"
arm7_path = "arm7 path"
arm9_path = "arm9 path"

firmware = "firmware"
file_path = "file path"
nickname = "nickname"
message = "message"
favorite_color = "favorite color"

scene_export = "scene export"
output_directory = "output directory"
shadow_polygons = "shadow polygons"

keyboard   = "keyboard"
controller = "controller"

a               = "a"
b               = "b"
select          = "select"
start           = "start"
left            = "left"
right           = "right"
up              = "up"
down            = "down"
l               = "l"
r               = "r"
x               = "x"
y               = "y"
hinge           = "hinge"
debug           = "debug"
layout_toggle   = "layout toggle"
sizing_toggle   = "sizing toggle"
rotation_toggle = "rotation toggle"
export_toggle   = "export toggle"

save = "save"

[settings.about]

about = "about"
version = "Version dev post-v0.0.3"
copyright = "© 2024 - 2026 Aaron Balke,\nlicensed under BSD 3-Clause License.\nGame Boy, Game Boy Advance, and Nintendo DS\nare registered trademarks of Nintendo Co., Ltd."
thank_yous = "Thank you Giovanni Bajo, Mireille Meyer,\nVicki Pfau, Martin Korth, and many more."
