// Code generated by '_gen'
package arm7

import (
	"math/bits"

	a "github.com/aabalke/gojit"
)

func (j *Jit) emitThumbAddSub(op uint16) {
	var (
		inst = (op >> 9) & 0b11
		rs   = uint32((op >> 3) & 7)
		rd   = uint32(op & 7)
	)

	j.LdrReg(a.R00, rs)

	switch inst {
	case THUMB_ADD:
		j.LdrReg(a.R01, uint32(op>>6)&7)
		j.ADDReg(a.R00, a.R00, a.R01, 0, 0, true, false, false)

	case THUMB_SUB:
		j.LdrReg(a.R01, uint32(op>>6)&7)
		j.SUBReg(a.R00, a.R00, a.R01, 0, 0, true, false, false)

	case THUMB_ADDImm:
		j.ADDImm(a.R00, a.R00, uint32(op>>6)&7, true, false, false)

	case THUMB_SUBImm:
		j.SUBImm(a.R00, a.R00, uint32(op>>6)&7, true, false, false)
	}

	j.StrReg(a.R00, rd)

	j.Cset(a.R00, a.V, false)
	j.StrFlag(a.R00, V)

	j.Cset(a.R00, a.C, false)
	j.StrFlag(a.R00, C)

	j.Cset(a.R00, a.N, false)
	j.StrFlag(a.R00, N)

	j.Cset(a.R00, a.Z, false)
	j.StrFlag(a.R00, Z)
}

func (j *Jit) emitThumbImm(op uint16) {
	var (
		inst = (op >> 11) & 0b11
		rd   = uint32(op>>8) & 0x7
		nn   = uint32(op & 0xFF)
	)

	if inst == THUMB_IMM_MOV {
		j.Movz(a.R00, nn, 0, false)
		j.StrReg(a.R00, rd)
		j.TstReg(a.R00, a.R00, 0, 0, false)

		j.Cset(a.R00, a.N, false)
		j.StrFlag(a.R00, N)

		j.Cset(a.R00, a.Z, false)
		j.StrFlag(a.R00, Z)
		return
	}

	j.LdrReg(a.R00, rd)

	switch inst {
	case THUMB_IMM_CMP:
		j.SUBImm(a.R00, a.R00, nn, true, false, false)

	case THUMB_IMM_ADD:
		j.ADDImm(a.R00, a.R00, nn, true, false, false)
		j.StrReg(a.R00, rd)

	case THUMB_IMM_SUB:
		j.SUBImm(a.R00, a.R00, nn, true, false, false)
		j.StrReg(a.R00, rd)
	}

	j.Cset(a.R00, a.V, false)
	j.StrFlag(a.R00, V)

	j.Cset(a.R00, a.C, false)
	j.StrFlag(a.R00, C)

	j.Cset(a.R00, a.N, false)
	j.StrFlag(a.R00, N)

	j.Cset(a.R00, a.Z, false)
	j.StrFlag(a.R00, Z)
}

func (j *Jit) emitThumbLSHalf(op uint16) {
	var (
		offset = uint32((op >> 6) & 0x1F << 1)
		rd     = uint32(op & 0x7)
	)

	j.LdrReg(a.R00, uint32(op>>3)&7)
	j.ADDImm(a.R00, a.R00, offset, false, false, false)

	if ldr := (op>>11)&1 != 0; ldr {
		j.MovReg(a.R08, a.R00, false)
		j.AndImm(a.R00, a.R00, a.EncodeImm(0xFFFF_FFFE, false), false, false)
		j.CallFunc(Read16)

		j.MovReg(a.R01, a.R08, false)
		j.AndImm(a.R01, a.R01, IMM_1, false, false)
		j.LslImm(a.R01, a.R01, 3, false)
		j.RorReg(a.R00, a.R00, a.R01, false)
		j.StrReg(a.R00, rd)

	} else {

		j.AndImm(a.R00, a.R00, a.EncodeImm(0xFFFF_FFFE, false), false, false)

		j.LdrReg(a.R01, rd)
		j.CallFunc(Write16)
	}
}

func (j *Jit) emitThumbSdt(op uint16) {
	var (
		inst = (op >> 10) & 0b11
		rd   = uint32(op & 0x7)
	)

	j.LdrReg(a.R00, uint32(op>>3)&7)
	j.LdrReg(a.R01, uint32(op>>6)&7)
	j.ADDReg(a.R00, a.R00, a.R01, 0, 0, false, false, false)

	if signed := (op>>9)&1 != 0; signed {

		switch inst {
		case THUMB_STRH:
			j.LdrReg(a.R01, rd)
			j.AndImm(a.R00, a.R00, a.EncodeImm(0xFFFF_FFFE, false), false, false)
			j.CallFunc(Write16)

		case THUMB_LDSB:

			// sign-expand byte value
			j.CallFunc(Read)
			j.Sxtb(a.R00, a.R00, false)
			j.StrReg(a.R00, rd)

		case THUMB_LDRH:

			j.MovReg(a.R08, a.R00, false)
			j.AndImm(a.R00, a.R00, a.EncodeImm(0xFFFF_FFFE, false), false, false)

			j.CallFunc(Read16)

			j.MovReg(a.R01, a.R08, false)
			j.AndImm(a.R01, a.R01, IMM_1, false, false)
			j.LslImm(a.R01, a.R01, 3, false)
			j.RorReg(a.R00, a.R00, a.R01, false)
			j.StrReg(a.R00, rd)

		case THUMB_LDSH:

			j.TstImm(a.R00, IMM_1, false)

			misaligned := j.BCond(a.NZ)

			// sign-expand half value
			j.AndImm(a.R00, a.R00, a.EncodeImm(0xFFFF_FFFE, false), false, false)
			j.CallFunc(Read16)
			j.Sxth(a.R00, a.R00, false)
			j.StrReg(a.R00, rd)

			byte := j.B()
			misaligned()

			// sign-expand byte value
			j.CallFunc(Read)
			j.Sxtb(a.R00, a.R00, false)
			j.StrReg(a.R00, rd)

			byte()

		}

		return
	}

	switch inst {
	case THUMB_STR_REG:
		j.LdrReg(a.R01, rd)
		j.AndImm(a.R00, a.R00, IMM_0xFFFF_FFFC, false, false)
		j.CallFunc(Write32)

	case THUMB_STRB_REG:
		j.LdrReg(a.R01, rd)
		j.CallFunc(Write)

	case THUMB_LDR_REG:
		j.MovReg(a.R08, a.R00, false)
		j.AndImm(a.R00, a.R00, IMM_0xFFFF_FFFC, false, false)

		j.CallFunc(Read32)

		j.MovReg(a.R01, a.R08, false)
		j.AndImm(a.R01, a.R01, IMM_3, false, false)
		j.LslImm(a.R01, a.R01, 3, false)
		j.RorReg(a.R00, a.R00, a.R01, false)
		j.StrReg(a.R00, rd)
	case THUMB_LDRB_REG:

		j.CallFunc(Read)
		j.StrReg(a.R00, rd)
	}
}

func (j *Jit) emitThumbLPC(op uint16) {
	var (
		rd = uint32(op>>8) & 0x7
		nn = uint32(op&0xFF) << 2
	)

	j.LdrReg(a.R00, PC)
	j.ADDImm(a.R00, a.R00, 4, false, false, false)
	j.AndImm(a.R00, a.R00, IMM_0xFFFF_FFFC, false, false)
	j.ADDImm(a.R00, a.R00, nn, false, false, false)

	j.CallFunc(Read32)

	j.StrReg(a.R00, rd)
}

func (j *Jit) emitThumbLSImm(op uint16) {
	var (
		inst = (op >> 11) & 0b11
		rd   = uint32(op & 0x7)
		rb   = uint32(op>>3) & 0x7
		nn   = uint32(op>>6) & 0x1F
	)

	j.LdrReg(a.R00, rb)

	switch inst {
	case THUMB_STR_IMM:
		j.ADDImm(a.R00, a.R00, nn<<2, false, false, false)
		j.AndImm(a.R00, a.R00, IMM_0xFFFF_FFFC, false, false)
		j.LdrReg(a.R01, rd)
		j.CallFunc(Write32)
	case THUMB_LDR_IMM:
		j.ADDImm(a.R00, a.R00, nn<<2, false, false, false)

		j.MovReg(a.R08, a.R00, false)

		j.AndImm(a.R00, a.R00, IMM_0xFFFF_FFFC, false, false)
		j.CallFunc(Read32)

		j.MovReg(a.R01, a.R08, false)
		j.AndImm(a.R01, a.R01, IMM_3, false, false)
		j.LslImm(a.R01, a.R01, 3, false)
		j.RorReg(a.R00, a.R00, a.R01, false)
		j.StrReg(a.R00, rd)

	case THUMB_STRB_IMM:
		j.ADDImm(a.R00, a.R00, nn, false, false, false)
		j.LdrReg(a.R01, rd)
		j.CallFunc(Write)
	case THUMB_LDRB_IMM:
		j.ADDImm(a.R00, a.R00, nn, false, false, false)
		j.CallFunc(Read)
		j.StrReg(a.R00, rd)
	}
}

func (j *Jit) emitThumbRelative(op uint16) {
	var (
		rd = uint32(op>>8) & 0x7
		nn = uint32(op&0xFF) << 2
	)

	if isSP := (op>>11)&1 != 0; isSP {

		j.LdrReg(a.R00, SP)
		j.ADDImm(a.R00, a.R00, nn, false, false, false)
		j.StrReg(a.R00, rd)

		return
	}

	j.LdrReg(a.R00, PC)
	j.ADDImm(a.R00, a.R00, 4, false, false, false)
	j.AndImm(a.R00, a.R00, IMM_0xFFFF_FFFC, false, false)
	j.ADDImm(a.R00, a.R00, nn, false, false, false)
	j.StrReg(a.R00, rd)
}

func (j *Jit) emitThumbStack(op uint16) {
	nn := uint32(op&0x7F) << 2

	j.LdrReg(a.R00, SP)

	if sub := (op>>7)&1 != 0; sub {
		j.SUBImm(a.R00, a.R00, nn, false, false, false)
	} else {
		j.ADDImm(a.R00, a.R00, nn, false, false, false)
	}

	j.StrReg(a.R00, SP)
}

func (j *Jit) emitThumbLSSP(op uint16) {
	rd := uint32(op>>8) & 0x7

	j.LdrReg(a.R00, SP)
	j.ADDImm(a.R00, a.R00, uint32(op&0xFF)<<2, false, false, false)

	if ldr := (op>>11)&1 != 0; ldr {

		j.MovReg(a.R08, a.R00, false)
		j.AndImm(a.R00, a.R00, IMM_0xFFFF_FFFC, false, false)
		j.CallFunc(Read32)

		j.MovReg(a.R01, a.R08, false)
		j.AndImm(a.R01, a.R01, IMM_1, false, false)
		j.LslImm(a.R01, a.R01, 3, false)
		j.RorReg(a.R00, a.R00, a.R01, false)
		j.StrReg(a.R00, rd)
	} else {
		j.LdrReg(a.R01, rd)
		j.CallFunc(Write32)
	}
}

func (j *Jit) emitThumbHiRegBX(op uint16) {
	var (
		inst = (op >> 8) & 0b11
		mSBd = (op>>7)&1 != 0
		mSBs = (op>>6)&1 != 0
		rs   = uint32(op>>3) & 0xF
		rd   = uint32(op & 0x7)
	)

	if rd == PC {
		panic("arm64 jit thumb hi pc == rd")
	}

	if inst != 3 && mSBd {
		rd |= 0b1000
	}

	if mSBs {
		rs |= 0b1000
	}

	switch inst {
	case HI_ADD:

		j.LdrReg(a.R00, rs)
		j.LdrReg(a.R01, rd)

		if rs == PC {
			j.ADDImm(a.R00, a.R00, 4, false, false, false)
		}

		j.ADDReg(a.R00, a.R00, a.R01, 0, 0, false, false, false)
		j.StrReg(a.R00, rd)

		return

	case HI_CMP:

		j.LdrReg(a.R00, rs)
		j.LdrReg(a.R01, rd)

		if rs == PC {
			j.ADDImm(a.R00, a.R00, 4, false, false, false)
		}

		j.SUBReg(a.R00, a.R01, a.R00, 0, 0, true, false, false)

		j.Cset(a.R00, a.V, false)
		j.StrFlag(a.R00, V)

		j.Cset(a.R00, a.C, false)
		j.StrFlag(a.R00, C)

		j.Cset(a.R00, a.N, false)
		j.StrFlag(a.R00, N)

		j.Cset(a.R00, a.Z, false)
		j.StrFlag(a.R00, Z)

		return

	case HI_MOV:

		if nop := rs == 8 && rd == 8; nop {
			return
		}

		j.LdrReg(a.R00, rs)

		if rs == PC {
			j.ADDImm(a.R00, a.R00, 4, false, false, false)
		}

		j.StrReg(a.R00, rd)

		return

	case HI_BX:
		panic("arm64 jit thumb hi bx")
	}
}

func (j *Jit) emitThumbShifted(op uint16) {
	var (
		shType = (op >> 11) & 0b11
		is     = uint32(op>>6) & 0x1F
		rs     = uint32(op>>3) & 7
		rd     = uint32(op) & 7
	)

	j.LdrReg(a.R00, rs)

	switch shType {
	case LSL:

		if is != 0 {

			j.MovReg(a.R01, a.R00, false)

			j.LsrImm(a.R01, a.R01, 32-is, false)

			j.TstImm(a.R01, IMM_1, false)

			j.Cset(a.R01, a.NZ, false)
			j.StrFlag(a.R01, C)

			j.LslImm(a.R00, a.R00, is, false)
		}

	case LSR:

		if is == 0 {
			j.LsrImm(a.R00, a.R00, 31, false)
			j.TstImm(a.R00, IMM_1, false)
			j.Cset(a.R00, a.NZ, false)
			j.StrFlag(a.R00, C)

			j.Movz(a.R00, 0, 0, false)
		} else {

			j.MovReg(a.R01, a.R00, false)

			j.LsrImm(a.R01, a.R01, is-1, false)

			j.TstImm(a.R01, IMM_1, false)

			j.Cset(a.R01, a.NZ, false)
			j.StrFlag(a.R01, C)

			j.LsrImm(a.R00, a.R00, is, false)
		}

	case ASR:

		if is == 0 {
			j.AsrImm(a.R00, a.R00, 31, false)
			j.TstImm(a.R00, IMM_1, false)
			j.Cset(a.R01, a.NZ, false)
			j.StrFlag(a.R01, C)
		} else {
			j.MovReg(a.R01, a.R00, false)

			j.AsrImm(a.R01, a.R01, is-1, false)

			j.TstImm(a.R01, IMM_1, false)

			j.Cset(a.R01, a.NZ, false)
			j.StrFlag(a.R01, C)

			j.AsrImm(a.R00, a.R00, is, false)
		}
	}

	j.StrReg(a.R00, rd)

	j.TstReg(a.R00, a.R00, 0, 0, false)

	j.Cset(a.R00, a.N, false)
	j.StrFlag(a.R00, N)

	j.Cset(a.R00, a.Z, false)
	j.StrFlag(a.R00, Z)
}

func (j *Jit) emitThumbAlu(op uint16) {
	var (
		rs = uint32(op>>3) & 7
		rd = uint32(op) & 7
	)

	switch inst := (op >> 6) & 0xF; inst {
	case THUMB_MUL:

		j.LdrReg(a.R00, rd)
		j.LdrReg(a.R01, rs)

		j.Mul(a.R00, a.R00, a.R01, false)

		j.StrReg(a.R00, rd)
		// ARM < 4, carry flag destroyed, ARM >= 5, carry flag unchanged
		// cpsr.C = false

		j.TstReg(a.R00, a.R00, 0, 0, false)

		j.Cset(a.R00, a.N, false)
		j.StrFlag(a.R00, N)

		j.Cset(a.R00, a.Z, false)
		j.StrFlag(a.R00, Z)

	case THUMB_TST:

		j.LdrReg(a.R00, rd)
		j.LdrReg(a.R01, rs)

		j.TstReg(a.R00, a.R01, 0, 0, false)

		j.Cset(a.R00, a.N, false)
		j.StrFlag(a.R00, N)

		j.Cset(a.R00, a.Z, false)
		j.StrFlag(a.R00, Z)

	case THUMB_CMN, THUMB_CMP, THUMB_NEG, THUMB_SBC, THUMB_ADC:

		j.LdrReg(a.R00, rd)
		j.LdrReg(a.R01, rs)

		switch inst {
		case THUMB_CMN:
			j.ADDReg(a.R00, a.R00, a.R01, 0, 0, true, false, false)
		case THUMB_CMP:
			j.CmpReg(a.R00, a.R01, 0, 0, false, false)
		case THUMB_NEG:
			j.NegReg(a.R00, a.R01, 0, 0, true, false, false)
			j.StrReg(a.R00, rd)
		case THUMB_ADC:
			j.LdrFlag(a.R08, C)
			j.LslImm(a.R08, a.R08, 29, false)
			j.Msr(a.R08)
			j.AdcReg(a.R00, a.R00, a.R01, true, false)
			j.StrReg(a.R00, rd)
		case THUMB_SBC:
			j.LdrFlag(a.R08, C)
			j.LslImm(a.R08, a.R08, 29, false)
			j.Msr(a.R08)
			j.SbcReg(a.R00, a.R00, a.R01, true, false)
			j.StrReg(a.R00, rd)
		}

		j.Cset(a.R00, a.C, false)
		j.StrFlag(a.R00, C)

		j.Cset(a.R00, a.V, false)
		j.StrFlag(a.R00, V)

		j.Cset(a.R00, a.N, false)
		j.StrFlag(a.R00, N)

		j.Cset(a.R00, a.Z, false)
		j.StrFlag(a.R00, Z)

	case THUMB_AND, THUMB_EOR, THUMB_ORR, THUMB_BIC, THUMB_MVN:
		j.LdrReg(a.R00, rd)
		j.LdrReg(a.R01, rs)

		switch inst {
		case THUMB_AND:
			j.AndReg(a.R00, a.R00, a.R01, 0, 0, true, false)
		case THUMB_EOR:
			j.EorReg(a.R00, a.R00, a.R01, 0, 0, false)
			j.TstReg(a.R00, a.R00, 0, 0, false)
		case THUMB_ORR:
			j.OrrReg(a.R00, a.R00, a.R01, 0, 0, false)
			j.TstReg(a.R00, a.R00, 0, 0, false)
		case THUMB_BIC:
			j.BicReg(a.R00, a.R00, a.R01, 0, 0, true, false)
		case THUMB_MVN:
			j.OrnReg(a.R00, a.RZR, a.R01, 0, 0, false)
			j.TstReg(a.R00, a.R00, 0, 0, false)
		}
		j.StrReg(a.R00, rd)

		j.Cset(a.R00, a.N, false)
		j.StrFlag(a.R00, N)

		j.Cset(a.R00, a.Z, false)
		j.StrFlag(a.R00, Z)

	case THUMB_LSL:
		j.LdrReg(a.R00, rd)
		j.LdrReg(a.R01, rs)

		j.AndImm(a.R01, a.R01, a.EncodeImm(0xFF, false), false, false)

		j.CmpImm(a.R01, 32, 0, false, false)

		g32 := j.BCond(a.GT)
		e32 := j.BCond(a.EQ)

		j.TstReg(a.R01, a.R01, 0, 0, false)
		zero := j.BCond(a.EQ)

		j.MovReg(a.R02, a.R00, false)
		j.LsrReg(a.R02, a.R00, a.R01, false)
		j.TstImm(a.R02, IMM_1, false)
		j.Cset(a.R02, a.NZ, false)
		j.StrFlag(a.R02, C)

		j.LslReg(a.R00, a.R00, a.R01, false)
		j.StrReg(a.R00, rd)

		skip := j.B()
		zero()

		j.LslReg(a.R00, a.R00, a.R01, false)
		j.StrReg(a.R00, rd)

		skip2 := j.B()

		e32()

		j.MovReg(a.R02, a.R00, false)
		j.TstImm(a.R02, IMM_1, false)
		j.Cset(a.R02, a.NZ, false)
		j.StrFlag(a.R02, C)

		j.Movz(a.R00, 0, 0, false)
		j.StrReg(a.R00, rd)

		skip3 := j.B()
		g32()

		j.Movz(a.R00, 0, 0, false)
		j.StrFlag(a.R00, C)
		j.StrReg(a.R00, rd)

		skip()
		skip2()
		skip3()

		j.TstReg(a.R00, a.R00, 0, 0, false)

		j.Cset(a.R00, a.N, false)
		j.StrFlag(a.R00, N)

		j.Cset(a.R00, a.Z, false)
		j.StrFlag(a.R00, Z)

	case THUMB_LSR, THUMB_ASR:
		j.LdrReg(a.R00, rd)
		j.LdrReg(a.R01, rs)

		j.AndImm(a.R01, a.R01, a.EncodeImm(0xFF, false), true, false)

		j.TstReg(a.R01, a.R01, 0, 0, false)

		zero := j.BCond(a.Z)

		j.SUBImm(a.R02, a.R01, 1, false, false, false)
		if inst == THUMB_LSR {
			j.LsrReg(a.R02, a.R00, a.R02, true)
		} else {
			j.AsrReg(a.R02, a.R00, a.R02, false)
		}
		j.TstImm(a.R02, IMM_1, false)
		j.Cset(a.R02, a.NZ, false)
		j.StrFlag(a.R02, C)

		zero()

		if inst == THUMB_LSR {
			j.LsrReg(a.R00, a.R00, a.R01, true)
		} else {
			j.AsrReg(a.R00, a.R00, a.R01, false)
		}
		j.StrReg(a.R00, rd)

		j.TstReg(a.R00, a.R00, 0, 0, false)

		j.Cset(a.R00, a.N, false)
		j.StrFlag(a.R00, N)

		j.Cset(a.R00, a.Z, false)
		j.StrFlag(a.R00, Z)

	case THUMB_ROR:
		j.LdrReg(a.R00, rd)
		j.LdrReg(a.R01, rs)

		j.AndImm(a.R01, a.R01, a.EncodeImm(0xFF, false), true, false)

		j.TstReg(a.R01, a.R01, 0, 0, false)

		zero := j.BCond(a.Z)

		// cpsr.C = (rdv>>((rsv-1)%32))&1 != 0
		j.SUBImm(a.R02, a.R01, 1, false, false, false)
		j.RorReg(a.R02, a.R00, a.R02, false)
		j.TstImm(a.R02, IMM_1, false)
		j.Cset(a.R02, a.NZ, false)
		j.StrFlag(a.R02, C)

		zero()

		j.RorReg(a.R00, a.R00, a.R01, false)
		j.StrReg(a.R00, rd)

		j.TstReg(a.R00, a.R00, 0, 0, false)

		j.Cset(a.R00, a.N, false)
		j.StrFlag(a.R00, N)

		j.Cset(a.R00, a.Z, false)
		j.StrFlag(a.R00, Z)
	}
}

func (j *Jit) emitThumbPushPop(op uint16) {
	var (
		pclr  = (op>>8)&1 != 0
		rlist = op & 0xFF
		pop   = (op>>11)&1 != 0
	)

	reg := uint32(0)
	if !pop {
		reg = 7
	}

	if !pop && pclr {

		j.LdrReg(a.R00, SP)
		j.SUBImm(a.R00, a.R00, 4, false, false, false)
		j.StrReg(a.R00, SP)

		j.LdrReg(a.R01, LR)
		j.CallFunc(Write32)
	}

	for range 8 {
		if disabled := (rlist>>reg)&1 == 0; disabled {
			if pop {
				reg++
			} else {
				reg--
			}
			continue
		}

		if pop {

			j.LdrReg(a.R00, SP)
			j.CallFunc(Read32)
			j.StrReg(a.R00, reg)

			j.LdrReg(a.R00, SP)
			j.ADDImm(a.R00, a.R00, 4, false, false, false)
			j.StrReg(a.R00, SP)

		} else {
			j.LdrReg(a.R00, SP)
			j.SUBImm(a.R00, a.R00, 4, false, false, false)
			j.StrReg(a.R00, SP)

			j.LdrReg(a.R01, reg)

			j.CallFunc(Write32)
		}

		if pop {
			reg++
		} else {
			reg--
		}
	}

	if pop && pclr {
		panic("arm jit pop with pclr")
	}
}

func (j *Jit) emitThumbBlock(op uint16) {
	var (
		ldmia = (op>>11)&1 != 0
		rb    = uint32(op>>8) & 7
		rlist = uint32(op & 0xFF)
	)

	if !ldmia {

		if rlist == 0 {
			j.LdrReg(a.R00, rb)
			j.LdrReg(a.R01, PC)

			j.ADDImm(a.R01, a.R01, 6, false, false, false)

			j.CallFunc(Write32)

			j.LdrReg(a.R00, rb)
			j.ADDImm(a.R00, a.R00, 0x40, false, false, false)
			j.StrReg(a.R00, rb)

			return
		}

		regCount := uint32(bits.OnesCount32(rlist))
		smallest := (rlist & -rlist) == 1<<rb
		matchingRb := (rlist>>rb)&1 == 1

		rbIdx := uint32(0)
		count := uint32(0)

		// r8 == addr, r9 == matchingAddr, r10 matchingValue

		j.LdrReg(a.R08, rb)
		j.MovReg(a.R09, a.R08, false)
		j.AndImm(a.R08, a.R08, IMM_0xFFFF_FFFC, false, false)

		for reg := range uint32(8) {
			if disabled := (rlist>>reg)&1 == 0; disabled {
				continue
			}

			if reg == rb {
				j.MovReg(a.R00, a.R08, false)
				j.LdrReg(a.R01, reg)

				j.CallFunc(Write32)

				j.LdrReg(a.R00, reg)
				j.ADDImm(a.R00, a.R00, 4, false, false, false)
				j.MovReg(a.R10, a.R00, false)

				j.MovReg(a.R09, a.R08, false)

				rbIdx = regCount - count

				j.LdrReg(a.R00, rb)
				j.ADDImm(a.R00, a.R00, 4, false, false, false)
				j.StrReg(a.R00, rb)

				j.ADDImm(a.R08, a.R08, 4, false, false, false)
				continue
			}

			j.MovReg(a.R00, a.R08, false)
			j.LdrReg(a.R01, reg)

			j.CallFunc(Write32)

			j.LdrReg(a.R00, rb)
			j.ADDImm(a.R00, a.R00, 4, false, false, false)
			j.StrReg(a.R00, rb)

			j.ADDImm(a.R08, a.R08, 4, false, false, false)
		}

		if smallest {

			j.MovReg(a.R00, a.R08, false)
			j.CallFunc(Read32)
			j.MovReg(a.R01, a.R00, false)
			j.SUBImm(a.R01, a.R01, regCount<<1, false, false, false)
			j.LdrReg(a.R00, rb)

			j.CallFunc(Write32)
			return
		}

		if matchingRb {
			j.MovReg(a.R00, a.R09, false)
			j.MovReg(a.R01, a.R10, false)
			j.ADDImm(a.R01, a.R01, rbIdx<<1, false, false, false)
			j.CallFunc(Write32)
			return
		}

		return
	}

	// addr == r08 / r00
	// rbValue == r09

	j.LdrReg(a.R08, rb)
	j.MovReg(a.R09, a.R08, false)
	j.AndImm(a.R08, a.R08, IMM_0xFFFF_FFFC, false, false)

	matchingRb := false

	if rlist == 0 {
		panic("arm jit ldmia && rlist == 0")
	}

	for reg := range uint32(8) {
		if disabled := (rlist>>reg)&1 == 0; disabled {
			continue
		}

		j.MovReg(a.R00, a.R08, false)
		j.CallFunc(Read32)
		j.StrReg(a.R00, reg)

		if reg == rb {
			matchingRb = true
			// do not remove this, needed for golden sun and others
			j.LdrReg(a.R09, rb)
		}

		j.LdrReg(a.R00, rb)
		j.ADDImm(a.R00, a.R00, 4, false, false, false)
		j.StrReg(a.R00, rb)

		j.ADDImm(a.R08, a.R08, 4, false, false, false)
	}

	if matchingRb {
		j.StrReg(a.R09, rb)
	}
}
