version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: default
    env:
      # We enable CGO only where it's likely to work on the default runner
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
    ignore:
      # Still ignoring ARM for now to get a successful green build
      - goos: windows
        goarch: arm64
    main: .
    binary: guac

archives:
  - formats: ["tar.gz"]
    format_overrides:
      - goos: windows
        formats: ["zip"]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - 'Merge pull request'
