// Code generated by '_gen'
package arm9

import (
	"fmt"
	"math"
	"math/bits"

	"github.com/aabalke/guac/emu/cpu/arm7"
	"github.com/aabalke/guac/emu/cpu/arm9/cp15"
)

func (c *Cpu) DecodeARM(op uint32) {
	cond := op >> 28

	if cond == 0xF {
		switch {
		case IsBlx(op):
			c.Blx(op)
			return
		case IsPld(op):
			panic("unsetup pld instruction")
		}
	}

	if !c.Reg.CPSR.CheckCond(cond) {
		c.Seq = arm7.SEQ
		return
	}

	switch {
	case (op>>24)&0xF == 0xF:
		c.Exception(arm7.VEC_SWI, arm7.MODE_SWI)
	case IsBkpt(op):
		c.Exception(arm7.VEC_PREFETCH, arm7.MODE_ABT)
	case IsCoDataReg(op):
		c.CoDataReg(op)
	case arm7.IsB(op):
		c.B(op)
	case arm7.IsBX(op):
		c.BX(op)
	case arm7.IsSDT(op):
		c.Sdt(op)
	case arm7.IsBlock(op):
		c.Block(op)
	case arm7.IsHalf(op):
		c.Half(op)
	case arm7.IsUndefined(op):
		c.Exception(arm7.VEC_UNDEFINED, arm7.MODE_UND)
	case arm7.IsPSR(op):
		c.Psr(op)
	case arm7.IsSWP(op):
		c.Swp(op)
	case arm7.IsMul(op):
		c.Mul(op)
	case IsCLZ(op):
		c.Clz(op)
	case IsQAlu(op):
		c.Qalu(op)
	case IsExtMul(op):
		c.ExtendedMul(op)
	case arm7.IsALU(op):
		// if alu is moved higher, breaks on overlap since compare inst need Set always
		// probably best to just build a decoded table and jump instead of decode on the fly
		c.Alu(op)
	default:
		panic(fmt.Sprintf("nds: unable to decode arm9 arm pc=%08X op=%08X", c.Reg.R[PC], op))
	}
}

func IsPld(op uint32) bool {
	return arm7.IsOpFormat(
		op,
		0b1111_1101_0111_0000_1111_0000_0000_0000,
		0b1111_0101_0101_0000_1111_0000_0000_0000,
	)
}

//go:inline
func IsBlx(op uint32) bool {
	return arm7.IsOpFormat(
		op,
		0b1111_1110_0000_0000_0000_0000_0000_0000,
		0b1111_1010_0000_0000_0000_0000_0000_0000,
	)
}

//go:inline
func IsBkpt(op uint32) bool {
	return arm7.IsOpFormat(
		op,
		0b1111_1111_1111_0000_0000_0000_1111_0000,
		0b1110_0001_0010_0000_0000_0000_0111_0000,
	)
}

//go:inline
func IsCLZ(op uint32) bool {
	return arm7.IsOpFormat(
		op,
		0b1111_1111_1111_0000_1111_1111_0000,
		0b0001_0110_1111_0000_1111_0001_0000,
	)
}

//go:inline
func IsQAlu(op uint32) bool {
	return arm7.IsOpFormat(
		op,
		0b1111_1001_0000_0000_1111_1111_0000,
		0b0001_0000_0000_0000_0000_0101_0000,
	)
}

//go:inline
func IsCoDataReg(op uint32) bool {
	return arm7.IsOpFormat(
		op,
		0b1111_0000_0000_0000_0000_0001_0000,
		0b1110_0000_0000_0000_0000_0001_0000,
	)
}

//go:inline
func IsExtMul(op uint32) bool {
	return arm7.IsOpFormat(
		op,
		0b1111_1001_0000_0000_0000_1001_0000,
		0b0001_0000_0000_0000_0000_1000_0000,
	)
}

const (
	SMLAxy = iota
	SMLAWySMLALWy
	SMLALxy
	SMULxy
)

// TODO: need to add proper idle and timings for all multiplications

func (c *Cpu) ExtendedMul(op uint32) {
	var (
		rd = (op >> 16) & 0xF
		rn = (op >> 12) & 0xF
		rs = (op >> 8) & 0xF
		rm = (op >> 0) & 0xF
		r  = &c.Reg.R
		x  = (op >> 5) & 1
		y  = (op >> 6) & 1
	)

	switch inst := (op >> 21) & 3; inst {
	case SMLAxy:

		rmV := int64(int16((r[rm] >> (16 * x)) & 0xFFFF))
		rsV := int64(int16((r[rs] >> (16 * y)) & 0xFFFF))
		rnV := int64(int32(r[rn]))
		res := (rmV * rsV) + rnV
		r[rd] = uint32(res)

		if res > math.MaxInt32 || res < math.MinInt32 {
			c.Reg.CPSR.Q = true
		}

	case SMLAWySMLALWy:

		rsV := int64(int16((r[rs] >> (16 * y) & 0xFFFF)))
		rmV := int64(int32(r[rm]))
		res := (rmV * rsV) >> 16

		if smulwa := x == 0; smulwa {
			res += int64(int32(r[rn]))

			if res > math.MaxInt32 || res < math.MinInt32 {
				c.Reg.CPSR.Q = true
			}
		}

		r[rd] = uint32(res)

	case SMLALxy:

		rsV := int64(int16((r[rs] >> (16 * y) & 0xFFFF)))
		rmV := int64(int16((r[rm] >> (16 * x) & 0xFFFF)))
		add := int64(int32(r[rd]))<<32 | int64(int32(r[rn]))
		res := (rsV * rmV) + add
		r[rd] = uint32(res >> 32)
		r[rn] = uint32(res)

	case SMULxy:

		rmV := int64(int16((r[rm] >> (16 * x)) & 0xFFFF))
		rsV := int64(int16((r[rs] >> (16 * y)) & 0xFFFF))
		res := rmV * rsV

		r[rd] = uint32(res)
	}
}

func (c *Cpu) Blx(op uint32) {
	r := &c.Reg.R
	r[LR] = r[PC] - 4
	r[PC] += uint32((int32(op) << 8) >> 6)

	// half offset
	r[PC] += ((op >> 24) & 1) << 1

	c.Reg.CPSR.T = true
	c.Reload16()
}

func (c *Cpu) BX(op uint32) {
	var (
		r  = &c.Reg.R
		rn = op & 0xF
	)

	switch inst := (op >> 4) & 0xF; inst {
	case arm7.INST_BX:
		r[PC] = r[rn]
	case arm7.INST_BXJ:
		panic("Unsupported BXJ Instruction")
	case arm7.INST_BLX:

		if rn == 14 {
			// Using BLX R14 is possible (sets PC=Old_LR, and New_LR=retadr).
			tmp := r[LR]
			r[LR] = r[PC] - 4
			r[PC] = tmp
		} else {
			r[LR] = r[PC] - 4
			r[PC] = r[rn]
		}
	}

	c.ToggleThumb()
}

func (c *Cpu) Half(op uint32) {
	var (
		r       = &c.Reg.R
		rn      = (op >> 16) & 0xF
		rd      = (op >> 12) & 0xF
		preFlag = (op>>24)&1 != 0
		inst    = (op >> 5) & 3
		wb      = (op>>21)&1 != 0 || !preFlag
		rnv     = r[rn]
		post    = rnv
	)

	var offset uint32
	if imm := (op>>22)&1 != 0; imm {
		offset = (op & 0xF) | ((op >> 4) & 0xF0)
	} else {
		offset = r[op&0xF]
	}

	if up := (op>>23)&1 != 0; up {
		post += offset
	} else {
		post -= offset
	}

	var addr uint32
	if preFlag {
		addr = post
	} else {
		addr = rnv
	}

	if load := (op>>20)&1 != 0; !load {
		rdv := r[rd]

		var rd2v uint32

		if inst == arm7.STRD {
			rd2v = r[rd+1]
		}

		if wb {
			r[rn] = post
		}

		switch inst {
		case arm7.STRH:
			c.Write16(addr, uint16(rdv))

		case arm7.LDRD:
			addr &^= 7
			r[rd+0] = c.Read32(addr + 0)
			r[rd+1] = c.Read32(addr + 4)
		case arm7.STRD:
			addr &^= 7
			c.Write32(addr+0, rdv)
			c.Write32(addr+4, rd2v)
		default:
			panic("unsupported half store reserved")
		}

		return
	}

	if wb {
		r[rn] = post
	}

	switch inst {
	case arm7.LDRH:
		r[rd] = uint32(c.Read16(addr))
	case arm7.LDRSB:
		r[rd] = uint32(int32(int8(c.Read8(addr))))
	case arm7.LDRSH:
		r[rd] = uint32(int32(int16(c.Read16(addr))))
	default:
		panic("unsupported half load reserved")
	}
}

const (
	QADD  = 0
	QSUB  = 2
	QDADD = 4
	QDSUB = 6
)

func (c *Cpu) Qalu(op uint32) {
	var (
		r    = &c.Reg.R
		inst = (op >> 20) & 0xF
		rnV  = int64(int32(r[(op>>16)&0xF]))
		rmV  = int64(int32(r[op&0xF]))
	)

	if double := inst >= 4; double {

		rnV *= 2

		switch {
		case rnV > math.MaxInt32:
			c.Reg.CPSR.Q = true
			rnV = math.MaxInt32
		case rnV < math.MinInt32:
			c.Reg.CPSR.Q = true
			rnV = math.MinInt32
		}
	}

	if inst == QADD || inst == QDADD {
		rnV += rmV
	} else {
		rnV = rmV - rnV
	}

	switch {
	case rnV > math.MaxInt32:
		c.Reg.CPSR.Q = true
		rnV = math.MaxInt32
	case rnV < math.MinInt32:
		c.Reg.CPSR.Q = true
		rnV = math.MinInt32
	}

	rd := (op >> 12) & 0xF
	r[rd] = uint32(rnV)
}

func (c *Cpu) Clz(op uint32) {
	c.Reg.R[(op>>12)&0xF] = uint32(bits.LeadingZeros32(c.Reg.R[op&0xF]))
}

func (c *Cpu) CoDataReg(op uint32) {
	var (
		reg = cp15.CpRegister{
			Op: uint8((op >> 21) & 0x7),
			Cn: uint8((op >> 16) & 0xF),
			Pn: uint8((op >> 8) & 0xF),
			Cp: uint8((op >> 5) & 0x7),
			Cm: uint8((op >> 0) & 0xF),
		}

		r  = &c.Reg.R
		rd = (op >> 12) & 0xF
	)

	if (op >> 28) == 0xF {
		panic("MRC2/MCR2")
	}

	if mrc := (op>>20)&1 != 0; mrc {
		r[rd] = c.Cp15.Read(&reg)
		return
	}

	if rd == 0 && (reg == cp15.HALT || reg == cp15.HALT2) {
		c.Halted = true
		return
	}

	c.Cp15.Write(&reg, &c.LowVector, r[rd])
}

func (c *Cpu) Block(op uint32) {
	var (
		r     = &c.Reg.R
		rlist = op & 0xFFFF
		rn    = (op >> 16) & 0xF
		up    = (op>>23)&1 != 0
	)

	if rlist == 0 {
		if up {
			r[rn] += 0x40
		} else {
			r[rn] -= 0x40
		}
		return
	}

	var (
		pre        = (op>>24)&1 != 0
		psr        = (op>>22)&1 != 0
		wb         = (op>>21)&1 != 0
		load       = (op>>20)&1 != 0
		pcIncluded = rlist&0x8000 != 0
		rnIncluded = (rlist>>rn)&1 != 0
		regCount   = uint32(bits.OnesCount32(rlist))
		bytes      = regCount * 4
		first      = bits.TrailingZeros32(rlist)
		last       = bits.Len32(rlist) - 1
		isOnly     = regCount == 1
		isLast     = uint32(last) == rn
		addr       = r[rn]
	)

	mode := c.Reg.CPSR.Mode
	forceUser := psr && (mode != arm7.MODE_USR && mode != arm7.MODE_SYS) && (!load || !pcIncluded)
	if forceUser {
		c.ModeSwitch(mode, arm7.MODE_USR)
	}

	rnNew := addr
	if up {
		rnNew += bytes
	} else {
		pre = !pre
		rnNew -= bytes
		addr -= bytes
	}

	seq := uint32(arm7.NONSEQ)
	for i := first; i < 0x10; i++ {
		if disabled := rlist&(1<<i) == 0; disabled {
			continue
		}
		if pre {
			addr += 4
		}
		if load {
			r[i] = c.Read32Block(addr, seq)
		} else {
			c.Write32Block(addr, r[i], seq)
		}
		if !pre {
			addr += 4
		}
		seq = arm7.SEQ
	}

	if forceUser {
		c.ModeSwitch(arm7.MODE_USR, mode)
	}

	if wb {
		if load && rnIncluded {
			// ARMv5 LDM: writeback only if Rb is the only reg, or not last.
			if isOnly || !isLast {
				r[rn] = rnNew
			}
		} else {
			r[rn] = rnNew
		}
	}

	if !load {
		return
	}

	c.Idle(1)

	if !pcIncluded {
		return
	}

	if c.Reg.CPSR.T {
		c.Reload16()
	} else {
		c.Reload32()
	}

	if !psr {
		//c.ToggleThumb()
		return
	}
	var (
		curr = c.Reg.CPSR.Mode
		spsr = c.Reg.SPSR[arm7.ModeBank[curr]]
		next = spsr.Mode
	)

	if curr == arm7.MODE_USR {
		panic("user mode ldm^")
	}

	c.Reg.CPSR = spsr
	c.ModeSwitch(curr, next)
}
