// Code generated by '_gen'
package arm9

import (
	"fmt"
	"math"
	"math/bits"

	"github.com/aabalke/guac/emu/cpu/arm9/cp15"
	"github.com/aabalke/guac/emu/gba/cpu"
)

func (c *Cpu) DecodeARM(op uint32) {
	if cond := op >> 28; cond == 0xF {
		switch {
		case IsBlx(op):
			c.Blx(op)
			return
		case cpu.IsSDT(op):
			c.Sdt(op)
			return
		}
	}

	if cond := op >> 28; !c.Reg.CPSR.CheckCond(cond) {
		c.Seq = cpu.SEQ
		return
	}

	switch {
	case (op>>24)&0xF == 0xF:
		c.Exception(cpu.VEC_SWI, cpu.MODE_SWI)
	case IsBkpt(op):
		c.Exception(cpu.VEC_PREFETCH, cpu.MODE_ABT)
	case IsCoDataReg(op):
		c.CoDataReg(op)
	case cpu.IsB(op):
		c.B(op)
	case cpu.IsBX(op):
		c.BX(op)
	case cpu.IsSDT(op):
		c.Sdt(op)
	case cpu.IsBlock(op):
		c.Block(op)
	case cpu.IsHalf(op):
		c.Half(op)
	case cpu.IsUD(op):
		c.Exception(cpu.VEC_UNDEFINED, cpu.MODE_UND)
	case cpu.IsPSR(op):
		c.Psr(op)
	case cpu.IsSWP(op):
		c.Swp(op)
	case cpu.IsMul(op):
		c.Mul(op)
	case IsCLZ(op):
		c.Clz(op)
	case IsQAlu(op):
		c.Qalu(op)
	case IsExtMul(op):
		c.ExtendedMul(op)
	case cpu.IsALU(op):
		// if alu is moved higher, breaks on overlap since compare inst need Set always
		// probably best to just build a decoded table and jump instead of decode on the fly
		c.Alu(op)
		c.SetAluPC(op)
	default:
		panic(fmt.Sprintf("nds: unable to decode arm9 arm pc=%08X op=%08X", c.Reg.R[PC], op))
	}
}

//go:inline
func IsBlx(op uint32) bool {
	return cpu.IsOpFormat(
		op,
		0b1111_1110_0000_0000_0000_0000_0000_0000,
		0b1111_1010_0000_0000_0000_0000_0000_0000,
	)
}

//go:inline
func IsBkpt(op uint32) bool {
	return cpu.IsOpFormat(
		op,
		0b1111_1111_1111_0000_0000_0000_1111_0000,
		0b1110_0001_0010_0000_0000_0000_0111_0000,
	)
}

//go:inline
func IsCLZ(op uint32) bool {
	return cpu.IsOpFormat(
		op,
		0b1111_1111_1111_0000_1111_1111_0000,
		0b0001_0110_1111_0000_1111_0001_0000,
	)
}

//go:inline
func IsQAlu(op uint32) bool {
	return cpu.IsOpFormat(
		op,
		0b1111_1001_0000_0000_1111_1111_0000,
		0b0001_0000_0000_0000_0000_0101_0000,
	)
}

//go:inline
func IsCoDataReg(op uint32) bool {
	return cpu.IsOpFormat(
		op,
		0b1111_0000_0000_0000_0000_0001_0000,
		0b1110_0000_0000_0000_0000_0001_0000,
	)
}

//go:inline
func IsExtMul(op uint32) bool {
	return cpu.IsOpFormat(
		op,
		0b1111_1001_0000_0000_0000_1001_0000,
		0b0001_0000_0000_0000_0000_1000_0000,
	)
}

func (c *Cpu) SetAluPC(op uint32) {
	if rd := (op >> 12) & 0xF; rd == PC {
		inst := (op >> 21) & 0xF

		if op&(1<<20) != 0 {
			c.ExitException(c.Reg.CPSR.Mode)
		}

		//if c.Reg.CPSR.T {
		//	c.Reg.R[PC] &^= 1
		//} else {
		//	c.Reg.R[PC] &^= 3
		//}
		if inst < 0b1000 || inst > 0b1011 {
			if c.Reg.CPSR.T {
				c.Reload16()
			} else {
				c.Reload32()
			}
		}
	}
}

const (
	SMLAxy = iota
	SMLAWySMLALWy
	SMLALxy
	SMULxy
)

// TODO: need to add proper idle and timings for all multiplications

func (c *Cpu) ExtendedMul(op uint32) {
	var (
		inst = (op >> 21) & 0x3
		rd   = (op >> 16) & 0xF
		rn   = (op >> 12) & 0xF
		rs   = (op >> 8) & 0xF
		rm   = (op >> 0) & 0xF
		r    = &c.Reg.R
		cpsr = &c.Reg.CPSR
		x    = (op >> 5) & 1
		y    = (op >> 6) & 1
	)

	switch inst {
	case SMLAxy:

		rmV := int64(int16((r[rm] >> (16 * x)) & 0xFFFF))
		rsV := int64(int16((r[rs] >> (16 * y)) & 0xFFFF))
		rnV := int64(int32(r[rn]))
		res := rmV * rsV
		res += rnV

		r[rd] = uint32(res)

		if res > math.MaxInt32 || res < math.MinInt32 {
			cpsr.Q = true
		}

	case SMLAWySMLALWy:

		rsV := int64(int16((r[rs] >> (16 * y) & 0xFFFF)))
		rmV := int64(int32(r[rm]))
		res := (rmV * rsV) >> 16

		if smulwa := x == 0; smulwa {
			add := int64(int32(r[rn]))

			if res+add > math.MaxInt32 || res+add < math.MinInt32 {
				cpsr.Q = true
			}

			res += add
		}

		r[rd] = uint32(res)

	case SMLALxy:

		rsV := int64(int16((r[rs] >> (16 * y) & 0xFFFF)))
		rmV := int64(int16((r[rm] >> (16 * x) & 0xFFFF)))

		res := rsV * rmV
		add := int64(int32(r[rd]))<<32 | int64(int32(r[rn]))
		res += add

		r[rd] = uint32(res >> 32)
		r[rn] = uint32(res)

	case SMULxy:

		rmV := int64(int16((r[rm] >> (16 * x)) & 0xFFFF))
		rsV := int64(int16((r[rs] >> (16 * y)) & 0xFFFF))

		res := rmV * rsV

		r[rd] = uint32(res)
	}
}

func (c *Cpu) Blx(op uint32) {
	r := &c.Reg.R
	r[LR] = r[PC] - 4

	r[PC] += uint32((int32(op) << 8) >> 6)

	// half offset
	r[PC] += ((op >> 24) & 1) << 1

	c.Reg.CPSR.T = true
	c.Reload16()
}

func (c *Cpu) BX(op uint32) {
	var (
		r    = &c.Reg.R
		inst = (op >> 4) & 0xF
		rn   = op & 0xF
	)

	switch inst {
	case cpu.INST_BX:
		r[PC] = r[rn]
	case cpu.INST_BXJ:
		panic("Unsupported BXJ Instruction")
	case cpu.INST_BLX:

		if rn == 14 {
			// Using BLX R14 is possible (sets PC=Old_LR, and New_LR=retadr).
			tmp := r[14]
			r[14] = r[PC] - 4
			r[PC] = tmp
		} else {
			r[14] = r[PC] - 4
			r[PC] = r[rn]
		}
	}

	c.ToggleThumb()
}

func (c *Cpu) Half(op uint32) {
	var (
		r       = &c.Reg.R
		rn      = (op >> 16) & 0xF
		rd      = (op >> 12) & 0xF
		preFlag = (op>>24)&1 != 0
		load    = (op>>20)&1 != 0
		inst    = (op >> 5) & 0b11
		wb      = (op>>21)&1 != 0 || !preFlag
		rnv     = r[rn]
		post    = rnv

		pre, offset uint32
	)

	if imm := (op>>22)&1 != 0; imm {
		offset = (op & 0xF) | ((op >> 4) & 0xF0)
	} else {
		offset = r[op&0xF]
	}

	if up := (op>>23)&1 != 0; up {
		post += offset
	} else {
		post -= offset
	}

	if preFlag {
		pre = post
	} else {
		pre = rnv
	}

	if inst == cpu.RESERVED {
		panic("unsupported half (reserved)")
	}

	if !load {
		rdv := r[rd]

		var rd2v uint32

		if inst == cpu.STRD {
			rd2v = r[rd+1]
		}

		if wb {
			r[rn] = post
		}

		switch inst {
		case cpu.STRH:
			c.Write16(pre, uint16(rdv))

		case cpu.LDRD:
			addr := pre &^ 7
			r[rd+0] = c.Read32(addr + 0)
			r[rd+1] = c.Read32(addr + 4)
		case cpu.STRD:
			addr := pre &^ 7
			c.Write32(addr+0, rdv)
			c.Write32(addr+4, rd2v)
		}

		return
	}

	if wb {
		r[rn] = post
	}

	switch inst {
	case cpu.LDRH:
		r[rd] = uint32(c.Read16(pre))
	case cpu.LDRSB:
		r[rd] = uint32(int32(int8(c.Read8(pre))))
	case cpu.LDRSH:
		r[rd] = uint32(int32(int16(c.Read16(pre))))
	}
}

const (
	QADD  = 0
	QSUB  = 2
	QDADD = 4
	QDSUB = 6
)

func (c *Cpu) Qalu(op uint32) {
	var (
		r    = &c.Reg.R
		inst = (op >> 20) & 0xF
		rnV  = int64(int32(r[(op>>16)&0xF]))
		rmV  = int64(int32(r[op&0xF]))
	)

	if double := inst >= 4; double {

		rnV *= 2

		if rnV > math.MaxInt32 {
			c.Reg.CPSR.Q = true
			rnV = math.MaxInt32
		}

		if rnV < math.MinInt32 {
			c.Reg.CPSR.Q = true
			rnV = math.MinInt32
		}
	}

	if inst == QADD || inst == QDADD {
		rnV += rmV
	} else {
		rnV = rmV - rnV
	}

	if rnV > math.MaxInt32 {
		c.Reg.CPSR.Q = true
		rnV = math.MaxInt32
	}

	if rnV < math.MinInt32 {
		c.Reg.CPSR.Q = true
		rnV = math.MinInt32
	}

	rd := (op >> 12) & 0xF
	r[rd] = uint32(rnV)
}

func (c *Cpu) Clz(op uint32) {
	c.Reg.R[(op>>12)&0xF] = uint32(bits.LeadingZeros32(c.Reg.R[op&0xF]))
}

func (c *Cpu) CoDataReg(op uint32) {
	var (
		reg = cp15.CpRegister{
			Op: uint8((op >> 21) & 0x7),
			Cn: uint8((op >> 16) & 0xF),
			Pn: uint8((op >> 8) & 0xF),
			Cp: uint8((op >> 5) & 0x7),
			Cm: uint8((op >> 0) & 0xF),
		}

		r  = &c.Reg.R
		rd = (op >> 12) & 0xF
	)

	if (op >> 28) == 0xF {
		panic("MRC2/MCR2")
	}

	if mrc := (op>>20)&1 == 1; mrc {
		r[rd] = c.Cp15.Read(&reg)
		return
	}

	if rd == 0 && (reg == cp15.HALT || reg == cp15.HALT2) {
		c.Halted = true
		return
	}

	c.Cp15.Write(&reg, &c.LowVector, r[rd])
}

// TODO: This needs to be "modernized"
func (c *Cpu) Block(op uint32) {
	var (
		r        = &c.Reg.R
		rlist    = op & 0xFFFF
		regCount = uint32(bits.OnesCount32(rlist))
		rn       = (op >> 16) & 0xF
		addr     = r[rn] &^ 0b11
		up       = (op>>23)&1 != 0
	)

	if rlist == 0 {

		if up {
			r[rn] += 0x40
			return
		}

		r[rn] -= 0x40
		return
	}

	var (
		pcIncluded = rlist&0x8000 != 0
		rnIncluded = (rlist>>rn)&1 != 0
		pre        = (op>>24)&1 != 0
		psr        = (op>>22)&1 != 0
		wb         = (op>>21)&1 != 0
		load       = (op>>20)&1 != 0
		forceUser  = psr && (c.Reg.CPSR.Mode != cpu.MODE_USR) && (!load || !pcIncluded)
		wbValue    = r[rn]
		// fiq switch has additional r8 - r12 use mode switch registers
		forceFIQSwitch = forceUser && c.Reg.CPSR.Mode == cpu.MODE_FIQ
	)

	if op == 0xE8A00004 {

		v := r[1]

		defer func() {
			if v != r[1] {
				fmt.Printf("R1 Before %08X After %08X\n", v, r[1])
			}
		}()
	}

	if up {
		wbValue += regCount * 4
	} else {
		wbValue -= regCount * 4
	}

	rnRef := &c.Reg.R[rn]
	switch {
	case forceFIQSwitch:

		switch {
		case rn == 13:
			rnRef = &c.Reg.SP[cpu.ModeBank[cpu.MODE_USR]]
		case rn == 14:
			rnRef = &c.Reg.LR[cpu.ModeBank[cpu.MODE_USR]]
		case rn >= 8:
			rnRef = &c.Reg.USR[rn-8]

		}

	case forceUser:
		switch {
		case rn == 13:
			rnRef = &c.Reg.SP[cpu.ModeBank[cpu.MODE_USR]]
		case rn == 14:
			rnRef = &c.Reg.LR[cpu.ModeBank[cpu.MODE_USR]]
		}
	}

	var (
		rnv = *rnRef
		reg = uint32(0)
	)

	if !up {
		reg = 15
	}

	for range 16 {

		if disabled := (rlist>>reg)&1 == 0; disabled {
			if up {
				reg++
			} else {
				reg--
			}
			continue
		}

		ref := &c.Reg.R[reg]
		switch {
		case forceFIQSwitch:

			switch {
			case reg == 13:
				ref = &c.Reg.SP[cpu.ModeBank[cpu.MODE_USR]]
			case reg == 14:
				ref = &c.Reg.LR[cpu.ModeBank[cpu.MODE_USR]]
			case reg >= 8:
				ref = &c.Reg.USR[reg-8]
			}

		case forceUser:
			switch {
			case reg == 13:
				ref = &c.Reg.SP[cpu.ModeBank[cpu.MODE_USR]]
			case reg == 14:
				ref = &c.Reg.LR[cpu.ModeBank[cpu.MODE_USR]]
			}
		}

		if pre {
			if up {
				addr += 4
			} else {
				addr -= 4
			}
		}

		if load {
			*ref = c.Read32(addr)
		} else {
			switch reg {
			case rn:
				c.Write32(addr, rnv)
			default:
				c.Write32(addr, *ref)
			}
		}

		if !pre {
			if up {
				addr += 4
			} else {
				addr -= 4
			}
		}

		if up {
			reg++
		} else {
			reg--
		}
	}

	if !load {
		if wb {
			r[rn] = wbValue
		}

		return
	}

	if wb {
		if rnIncluded {
			isLast := (rlist < (1 << (rn + 1)))
			isOnly := regCount == 1
			if !isLast || isOnly {
				r[rn] = wbValue
			}
		} else {
			r[rn] = wbValue
		}
	}

	if !pcIncluded {
		return
	}

	if !psr {
		c.ToggleThumb()
		return
	}

	var (
		curr = c.Reg.CPSR.Mode
		spsr = c.Reg.SPSR[cpu.ModeBank[curr]]
		next = spsr.Mode
	)

	c.Reg.CPSR = spsr

	if curr == cpu.MODE_USR {
		panic("USER MODE LDM PC CHANGE")
	}

	c.ModeSwitch(curr, next)

	if c.Reg.CPSR.T {
		c.Reload16()
	} else {
		c.Reload32()
	}
}
