// Code generated by '_gen'
package arm9

import (
	"github.com/aabalke/guac/emu/cpu"
	"github.com/aabalke/guac/emu/cpu/arm9/cp15"
)

type Cpu struct {
	Cp15      *cp15.Cp15
	Reg       Reg
	mem       cpu.MemoryInterface
	Halted    bool
	LowVector bool
	IrqLine   bool
}

const (
	SP = 13
	LR = 14
	PC = 15

	FLAG_N = 31
	FLAG_Z = 30
	FLAG_C = 29
	FLAG_V = 28
	FLAG_Q = 27
	FLAG_I = 7
	FLAG_F = 6
	FLAG_T = 5

	MODE_USR = 0x10
	MODE_FIQ = 0x11
	MODE_IRQ = 0x12
	MODE_SWI = 0x13
	MODE_ABT = 0x17
	MODE_UND = 0x1B
	MODE_SYS = 0x1F
)

func (cpu *Cpu) CheckCond(cond uint32) bool {
	cpsr := &cpu.Reg.CPSR

	switch cond {
	case 0xE: // AL (always)
		return true
	case 0x0: // EQ
		return cpsr.Z
	case 0x1: // NE
		return !cpsr.Z
	case 0x2: // CS/HS
		return cpsr.C
	case 0x3: // CC/LO
		return !cpsr.C
	case 0x4: // MI
		return cpsr.N
	case 0x5: // PL
		return !cpsr.N
	case 0x6: // VS
		return cpsr.V
	case 0x7: // VC
		return !cpsr.V
	case 0x8: // HI
		return cpsr.C && !cpsr.Z
	case 0x9: // LS
		return !cpsr.C || cpsr.Z
	case 0xA: // GE
		return cpsr.N == cpsr.V
	case 0xB: // LT
		return cpsr.N != cpsr.V
	case 0xC: // GT
		return !cpsr.Z && (cpsr.N == cpsr.V)
	case 0xD: // LE
		return cpsr.Z || (cpsr.N != cpsr.V)
	default: // NV
		return false
	}
}

var BANK_ID = map[uint32]uint32{
	MODE_USR: 0,
	MODE_SYS: 0,
	MODE_FIQ: 1,
	MODE_IRQ: 2,
	MODE_SWI: 3,
	MODE_ABT: 4,
	MODE_UND: 5,
}

func NewCpu(m cpu.MemoryInterface, cp15 *cp15.Cp15) *Cpu {
	c := &Cpu{
		mem:  m,
		Cp15: cp15,
	}

	return c
}

func (c *Cpu) Execute() (int, bool) {
	if c.IrqLine {
		c.Halted = false

		if !c.Reg.CPSR.I {
			if c.Reg.CPSR.T {
				c.mem.Read16(c.Reg.R[PC])
			} else {
				c.mem.Read32(c.Reg.R[PC])
			}

			c.Exception(VEC_IRQ, MODE_IRQ)
		}
	}

	if c.Reg.CPSR.T {
		return c.DecodeTHUMB()
	}

	return c.DecodeARM()
}

type Reg struct {
	R    [16]uint32
	SP   [6]uint32
	LR   [6]uint32
	FIQ  [5]uint32 // r8 - r12
	USR  [5]uint32 // r8 - r12 // tmp to restore after FIQ
	CPSR Cond
	SPSR [6]Cond
}

type Cond struct {
	N, Z, C, V, Q, I, F, T bool
	Mode                   uint32
}

//go:nosplit
func (c *Cond) Get() uint32 {
	v := c.Mode

	if c.N {
		v |= 1 << FLAG_N
	}
	if c.Z {
		v |= 1 << FLAG_Z
	}
	if c.C {
		v |= 1 << FLAG_C
	}
	if c.V {
		v |= 1 << FLAG_V
	}
	if c.Q {
		v |= 1 << FLAG_Q
	}
	if c.I {
		v |= 1 << FLAG_I
	}
	if c.F {
		v |= 1 << FLAG_F
	}
	if c.T {
		v |= 1 << FLAG_T
	}

	return v
}

func (c *Cond) Set(v uint32) {
	c.N = (v>>FLAG_N)&1 != 0
	c.Z = (v>>FLAG_Z)&1 != 0
	c.C = (v>>FLAG_C)&1 != 0
	c.V = (v>>FLAG_V)&1 != 0
	c.Q = (v>>FLAG_Q)&1 != 0
	c.I = (v>>FLAG_I)&1 != 0
	c.F = (v>>FLAG_F)&1 != 0
	c.T = (v>>FLAG_T)&1 != 0
	c.Mode = v & 0x1F
}

func (cpu *Cpu) toggleThumb() {
	r := &cpu.Reg.R
	cpsr := &cpu.Reg.CPSR

	cpsr.T = r[PC]&1 != 0

	if cpsr.T {
		r[PC] &^= 1
		return
	}

	r[PC] &^= 3
}
