// Code generated by '_gen'
package arm9

import (
	"github.com/aabalke/guac/emu/cpu"
	"github.com/aabalke/guac/emu/cpu/arm7"
	"github.com/aabalke/guac/emu/cpu/arm9/cp15"
)

type Cpu struct {
	arm7.Cpu
	Cp15 *cp15.Cp15
}

const (
	SP = 13
	LR = 14
	PC = 15

	FLAG_N = 31
	FLAG_Z = 30
	FLAG_C = 29
	FLAG_V = 28
	FLAG_Q = 27
	FLAG_I = 7
	FLAG_F = 6
	FLAG_T = 5
)

func NewCpu(jitEnabled bool, m cpu.MemoryInterface, irq *cpu.Irq, cp15 *cp15.Cp15) *Cpu {
	c := &Cpu{
		Cp15: cp15,
	}

	c.Irq = irq
	c.JitEnabled = jitEnabled
	c.Mem = m

	// skip bios
	c.Irq.IME = true

	return c
}

func (c *Cpu) Execute() (int, bool) {
	if c.Reg.CPSR.T {
		return c.DecodeTHUMB()
	}

	return c.DecodeARM()
}

func DecodeTHUMBBranch(op uint16) bool {
	switch {
	case isthumbSWI(op):
		return false
	case isThumbAddSub(op):
		return true
	case isThumbShift(op):
		return true
	case isThumbImm(op):
		return true
	case isThumbAlu(op):
		return true
	case isThumbHiReg(op):

		var (
			inst = (op >> 8) & 0b11
			mSBd = (op>>7)&1 != 0
			rd   = op & 0x7
		)

		if inst != 3 && mSBd {
			rd |= 0b1000
		}

		if inst == 3 || rd == PC {
			return false
		}

		return true
	case isLSHalf(op):
		return true
	case isThumbSdt(op):
		return true
	case isLPC(op):
		return true
	case isLSImm(op):
		return true
	case isPushPop(op):
		pclr := (op>>8)&1 != 0
		pop := (op>>11)&1 != 0
		if pop && pclr {
			return false
		}

		return true
	case isRelative(op):
		return true
	case isThumbB(op):
		return false
	case isJumpCall(op):
		return false
	case isStack(op):
		return true
	case isLongBranch(op):
		return false
	case isShortLongBranch(op):
		return false
	case isLSSP(op):
		return true
	case isMulti(op):

		ldmia := (op>>11)&1 != 0
		rlist := op & 0xFF

		if ldmia && rlist == 0 {
			return false
		}

		return true
	}

	return false
}
