// Code generated by '_gen'
package arm9

import (
	"github.com/aabalke/guac/config"

	"github.com/aabalke/guac/emu/cpu/arm7"
	"github.com/aabalke/guac/emu/cpu/arm9/cp15"
)

const (
	ADDRESS_SPACE = 0x1_0000_0000
	PAGE_SHIFT    = 16
)

var CpuPtr *Cpu

type Jit struct {
	arm7.Jit
	Cpu *Cpu

	BlockCache   *BlockCache
	Pages        []*Page
	Metrics      [ADDRESS_SPACE >> PAGE_SHIFT][]uint32
	invalidPages []*Page

	// used for testing individual instructions
	testFunc func()

	LoopThreshold uint32
	PageShift     uint32
	PageMask      uint32
}

type Page struct {
	id     uint32
	Blocks []*JitBlock
	dead   bool
}

func NewJit(cpu *Cpu) *Jit {
	const (
		PAGE_SIZE  = 0x10000
		PAGE_SHIFT = 16
		PAGE_MASK  = (1 << PAGE_SHIFT) - 1
	)

	CpuPtr = cpu

	if !cpu.JitEnabled {
		j := &Jit{Cpu: cpu}
		return j
	}

	return &Jit{
		Cpu:   cpu,
		Pages: make([]*Page, ADDRESS_SPACE>>PAGE_SHIFT),
		BlockCache: InitBlockCache(
			config.Conf.Nds.Jit.BlockCnt,
			PAGE_SIZE,
		),
		LoopThreshold: config.Conf.Nds.Jit.LoopCnt,
		PageShift:     PAGE_SHIFT,
		PageMask:      PAGE_MASK,
	}
}

func (j *Jit) Close() {
	if j.BlockCache != nil {
		j.BlockCache.Close()
	}
}

func (j *Jit) InvalidatePage(addr uint32) {
	if j.Pages == nil {
		return
	}

	page := j.Pages[addr>>j.PageShift]
	if page == nil || page.dead {
		return
	}

	page.dead = true

	j.Pages[addr>>j.PageShift] = nil
	j.Metrics[addr>>j.PageShift] = make([]uint32, (1<<j.PageShift)>>1)
	j.invalidPages = append(j.invalidPages, page)
}

func (j *Jit) DeletePages() {
	if len(j.invalidPages) == 0 {
		return
	}

	for _, page := range j.invalidPages {
		for i := range page.Blocks {

			block := page.Blocks[i]
			if block == nil {
				continue
			}

			page.Blocks[i] = nil

			if block.Skip {
				continue
			}

			j.BlockCache.InvalidateBlock(block)
		}
	}

	j.invalidPages = j.invalidPages[:0]
}

//go:nosplit
func Read(addr uint32) uint32 {
	return CpuPtr.Mem.Read8(addr)
}

//go:nosplit
func Read16(addr uint32) uint32 {
	return CpuPtr.Mem.Read16(addr)
}

//go:nosplit
func Read32(addr uint32) uint32 {
	return CpuPtr.Mem.Read32(addr)
}

//go:nosplit
func Write(addr uint32, v uint8) {
	CpuPtr.Mem.Write8(addr, v)
}

//go:nosplit
func Write16(addr uint32, v uint16) {
	CpuPtr.Mem.Write16(addr, v)
}

//go:nosplit
func Write32(addr, v uint32) {
	CpuPtr.Mem.Write32(addr, v)
}

//go:nosplit
func ReadCp15(op, cn, pn, cp, cm uint8) uint32 {
	reg := cp15.CpRegister{
		Op: op,
		Cn: cn,
		Pn: pn,
		Cp: cp,
		Cm: cm,
	}
	return CpuPtr.Cp15.Read(&reg)
}

//go:nosplit
func WriteCp15(op, cn, pn, cp, cm uint8, v uint32) {
	reg := cp15.CpRegister{
		Op: op,
		Cn: cn,
		Pn: pn,
		Cp: cp,
		Cm: cm,
	}
	CpuPtr.Cp15.Write(&reg, &CpuPtr.LowVector, v)
}

//go:nosplit
func GetSpsr(mode uint32) uint32 {
	return CpuPtr.Reg.SPSR[arm7.BANK_ID[mode]].Get()
}

func (j *Jit) UpdateMetrics(pc uint32, thumb bool) {
	pageIdx := pc >> j.PageShift
	blockIdx := (pc & j.PageMask) >> 1 // aligned to word for thumb

	if metrics := j.Metrics[pageIdx]; metrics == nil {
		j.Metrics[pageIdx] = make([]uint32, (1<<j.PageShift)>>1)
	}

	j.Metrics[pageIdx][blockIdx]++
	if j.Metrics[pageIdx][blockIdx] <= j.LoopThreshold {
		return
	}

	j.CreateBlock(pc, thumb)
}
