// Code generated by '_gen'
package arm9

import (
	"fmt"
	"os"
	"unsafe"

	a "github.com/aabalke/gojit/arm64"
	"github.com/aabalke/gojit/arm64/cache"
	"github.com/aabalke/guac/config"
)

var (
	CpuPtr      *Cpu
	CPU         = a.R15
	REG         = uint32(unsafe.Offsetof(Cpu{}.Reg))
	R           = REG + uint32(unsafe.Offsetof(Reg{}.R))
	CPSR        = REG + uint32(unsafe.Offsetof(Reg{}.CPSR))
	SCRATCH     = uint32(unsafe.Offsetof(Cpu{}.Scratch))
	HALTED_FLAG = uint32(unsafe.Offsetof(Cpu{}.Halted))

	MODE = CPSR + uint32(unsafe.Offsetof(Cond{}.Mode))
	N    = CPSR + uint32(unsafe.Offsetof(Cond{}.N))
	Z    = CPSR + uint32(unsafe.Offsetof(Cond{}.Z))
	C    = CPSR + uint32(unsafe.Offsetof(Cond{}.C))
	V    = CPSR + uint32(unsafe.Offsetof(Cond{}.V))
	Q    = CPSR + uint32(unsafe.Offsetof(Cond{}.Q))
	I    = CPSR + uint32(unsafe.Offsetof(Cond{}.I))
	F    = CPSR + uint32(unsafe.Offsetof(Cond{}.F))
	T    = CPSR + uint32(unsafe.Offsetof(Cond{}.T))
)

type Jit struct {
	*a.Assembler
	Cpu *Cpu

	// used for testing individual instructions
	testFunc func()
}

func NewJit(cpu *Cpu) *Jit {

	const (
		PAGE_SIZE  = 0x10000
		PAGE_SHIFT = 16
		PAGE_MASK  = (1 << PAGE_SHIFT) - 1
	)

	CpuPtr = cpu

	if !cpu.jitEnabled {
		j := &Jit{Cpu: cpu}
		return j
	}

	return &Jit{
		Cpu: cpu,
	}
}

func (j *Jit) Close() {}

func (j *Jit) InvalidatePage(addr uint32) {}

func (j *Jit) DeletePages() {}


const (
	IMM_BYTE = 4
	IMM_HALF = 2
	IMM_WORD = 1
	IMM_DWRD = 0.5
)

func (j *Jit) RegOffset(i, size uint32) uint32 {
	// 1 bytes, 2 half, 4 word, 8 double 16 q
	return R + i * size
}

func (j *Jit) LdrReg(reg a.Reg, emuReg uint32) {
	j.LdrImm(reg, CPU, j.RegOffset(emuReg, IMM_WORD), a.SIZE_WORD, false, true)
}

func (j *Jit) StrReg(reg a.Reg, emuReg uint32) {
	j.StrImm(reg, CPU, j.RegOffset(emuReg, IMM_WORD), a.SIZE_WORD, false, true)
}

func (j *Jit) LdrFlag(reg a.Reg, emuFlag uint32) {
	j.LdrImm(reg, CPU, emuFlag, a.SIZE_BYTE, false, true)
}

func (j *Jit) StrFlag(reg a.Reg, emuFlag uint32) {
	j.StrImm(reg, CPU, emuFlag, a.SIZE_BYTE, false, true)
}

func (j *Jit) TestInst(op uint32, f func(op uint32)) {

	asm, err := a.New(a.PageSize)
	if err != nil {
		panic(err)
	}

	j.Assembler = asm

	j.Mov64(CPU, uint64(uintptr(unsafe.Pointer(CpuPtr))))

	f(op)

	j.Ret()

	if err := asm.Error(); err != nil {
		panic(err)
	}

	cache.ClearICache(asm.Buf)

	a.CallJit(uintptr(unsafe.Pointer(&asm.Buf[0])))

	asm.Release()
}

var (
	rpc uint32
	sav Reg
	sta Reg
)

func (j *Jit) StartTest(op uint32, compare bool, f func(op uint32)) {

	if config.Conf.Nds.Jit.Enabled {
		panic("Jit Instruction Test is running with Jit Running")
	}

	if !compare {
		return
	}

	fmt.Printf("starting test %08X\n", op)

	cpu := j.Cpu
	rpc = cpu.Reg.R[15]
	sta = cpu.Reg

	cpu.Jit.TestInst(op, f)

	sav = cpu.Reg

	cpu.Reg = sta
}

func (j *Jit) EndTest(op uint32, compare bool) {

	cpu := j.Cpu

	sav.R[15] += 4

	if !(compare && cpu.Reg != sav) {
		return
	}

	fmt.Printf("STA REG %08X CPSR %08X\n", sta.R, sta.CPSR.Get())
	fmt.Printf("JIT REG %08X CPSR %08X\n", sav.R, sav.CPSR.Get())
	fmt.Printf("COR REG %08X CPSR %08X\n", cpu.Reg.R, cpu.Reg.CPSR.Get())
	fmt.Sprintf("Bad Compare %08X %08X", rpc, op)
	os.Exit(0)
}


//compare := true
//cpu.Jit.StartTest(op, compare, cpu.Jit.emitClz)
//defer cpu.Jit.EndTest(op, compare)
