// Code generated by '_gen'
package arm9

import (
	"fmt"

	"github.com/aabalke/guac/emu/cpu/arm7"
)

func (c *Cpu) DecodeTHUMB() (int, bool) {
	op, cycles := c.GetOpThumb()

	switch {
	case isThumbBkpt(op):
		panic("unsetup arm9 thumb bkpt")

	case isthumbSWI(op):
		c.Exception(arm7.VEC_SWI, arm7.MODE_SWI)
	case isThumbAddSub(op):
		c.ThumbAddSub(op)
	case isThumbShift(op):
		c.ThumbShifted(op)
	case isThumbImm(op):
		c.ThumbImm(op)
	case isThumbAlu(op):
		c.ThumbAlu(op)
	case isThumbHiReg(op):
		c.HiRegBX(op)
	case isLSHalf(op):
		c.ThumbLSHalf(op)
	case isThumbSdt(op):
		c.ThumbSdt(op)
	case isLPC(op):
		c.ThumbLPC(op)
	case isLSImm(op):
		c.ThumbLSImm(op)
	case isPushPop(op):
		c.ThumbPushPop(op)
	case isRelative(op):
		c.ThumbRelative(op)
	case isThumbB(op):
		c.ThumbB(op)
	case isJumpCall(op):
		c.ThumbJumpCalls(op)
	case isStack(op):
		c.ThumbStack(op)
	case isLongBranch(op):
		c.ThumbLongBranch(op)
	case isShortLongBranch(op):
		c.ThumbShortLongBranch(op)
	case isLSSP(op):
		c.ThumbLSSP(op)
	case isMulti(op):
		c.ThumbBlock(op)
	default:
		r := &c.Reg.R
		fmt.Printf("Unable to Decode ARM true %04X, at PC %08X\n", op, r[PC])
		return 0, false
	}

	return cycles + 1, true
}

//go:inline
func isThumbOpFormat(op, mask, fmt uint16) bool {
	return op&mask == fmt
}

//go:inline
func isThumbBkpt(op uint16) bool {
	return isThumbOpFormat(
		op,
		0b1011_1110_0000_0000,
		0b1111_1111_0000_0000,
	)
}

//go:inline
func isThumbShift(op uint16) bool {
	return isThumbOpFormat(
		op,
		0b1110_0000_0000_0000,
		0b0000_0000_0000_0000,
	)
}

//go:inline
func isThumbAddSub(op uint16) bool {
	return isThumbOpFormat(
		op,
		0b1111_1000_0000_0000,
		0b0001_1000_0000_0000,
	)
}

//go:inline
func isThumbImm(op uint16) bool {
	return isThumbOpFormat(
		op,
		0b1110_0000_0000_0000,
		0b0010_0000_0000_0000,
	)
}

//go:inline
func isThumbAlu(op uint16) bool {
	return isThumbOpFormat(
		op,
		0b1111_1100_0000_0000,
		0b0100_0000_0000_0000,
	)
}

//go:inline
func isThumbHiReg(op uint16) bool {
	return isThumbOpFormat(
		op,
		0b1111_1100_0000_0000,
		0b0100_0100_0000_0000,
	)
}

//go:inline
func isLSHalf(op uint16) bool {
	return isThumbOpFormat(
		op,
		0b1111_0000_0000_0000,
		0b1000_0000_0000_0000,
	)
}

//go:inline
func isThumbSdt(op uint16) bool {
	return isThumbOpFormat(
		op,
		0b1111_0000_0000_0000,
		0b0101_0000_0000_0000,
	)
}

//go:inline
func isLPC(op uint16) bool {
	return isThumbOpFormat(
		op,
		0b1111_1000_0000_0000,
		0b0100_1000_0000_0000,
	)
}

//go:inline
func isLSImm(op uint16) bool {
	return isThumbOpFormat(
		op,
		0b1110_0000_0000_0000,
		0b0110_0000_0000_0000,
	)
}

//go:inline
func isPushPop(op uint16) bool {
	return isThumbOpFormat(
		op,
		0b1111_0110_0000_0000,
		0b1011_0100_0000_0000,
	)
}

//go:inline
func isRelative(op uint16) bool {
	return isThumbOpFormat(
		op,
		0b1111_0000_0000_0000,
		0b1010_0000_0000_0000,
	)
}

//go:inline
func isJumpCall(op uint16) bool {
	return isThumbOpFormat(
		op,
		0b1111_0000_0000_0000,
		0b1101_0000_0000_0000,
	)
}

//go:inline
func isThumbB(op uint16) bool {
	return isThumbOpFormat(
		op,
		0b1111_1000_0000_0000,
		0b1110_0000_0000_0000,
	)
}

//go:inline
func isStack(op uint16) bool {
	return isThumbOpFormat(
		op,
		0b1111_1111_0000_0000,
		0b1011_0000_0000_0000,
	)
}

//go:inline
func isLongBranch(op uint16) bool {
	return isThumbOpFormat(
		op,
		0b1111_1000_0000_0000,
		0b1111_0000_0000_0000,
	)
}

//go:inline
func isShortLongBranch(op uint16) bool {
	return isThumbOpFormat(
		op,
		0b1111_1000_0000_0000,
		0b1111_1000_0000_0000,
	)
}

//go:inline
func isLSSP(op uint16) bool {
	return isThumbOpFormat(
		op,
		0b1111_0000_0000_0000,
		0b1001_0000_0000_0000,
	)
}

//go:inline
func isMulti(op uint16) bool {
	return isThumbOpFormat(
		op,
		0b1111_0000_0000_0000,
		0b1100_0000_0000_0000,
	)
}

//go:inline
func isthumbSWI(op uint16) bool {
	return isThumbOpFormat(
		op,
		0b1111_1111_0000_0000,
		0b1101_1111_0000_0000,
	)
}
