// Code generated by '_gen'
package arm9

import (
	"math/bits"
	"unsafe"
)

const (
	THUMB_STRH = iota
	THUMB_LDSB
	THUMB_LDRH
	THUMB_LDSH
)

const (
	THUMB_STR_REG = iota
	THUMB_STRB_REG
	THUMB_LDR_REG
	THUMB_LDRB_REG
)

func (cpu *Cpu) ThumbSdt(op uint16) {
	var (
		r    = &cpu.Reg.R
		inst = (op >> 10) & 0b11
		rd   = op & 0x7
		addr = r[(op>>3)&0x7] + r[(op>>6)&0x7]
	)

	if signed := (op>>9)&1 != 0; signed {

		switch inst {
		case THUMB_STRH:

			cpu.Mem.Write16(addr&^1, uint16(r[rd]))

		case THUMB_LDSB:

			// sign-expand byte value
			r[rd] = uint32(int32(int8(cpu.Mem.Read8(addr))))

		case THUMB_LDRH:

			v := cpu.Mem.Read16(addr &^ 1)
			is := (addr & 1) << 3
			r[rd] = bits.RotateLeft32(v, -int(is))

		case THUMB_LDSH:

			// sign-expand half value
			r[rd] = uint32(int32(int16(cpu.Mem.Read16(addr &^ 1))))

		}

		r[PC] += 2

		return
	}

	switch inst {
	case THUMB_STR_REG:
		cpu.Mem.Write32(addr&^0b11, r[rd])
	case THUMB_STRB_REG:
		cpu.Mem.Write8(addr, uint8(r[rd]))
	case THUMB_LDR_REG:
		v := cpu.Mem.Read32(addr &^ 0b11)
		is := (addr & 0b11) << 3
		r[rd] = bits.RotateLeft32(v, -int(is))
	case THUMB_LDRB_REG:
		r[rd] = cpu.Mem.Read8(addr)
	}

	r[PC] += 2
}

func (cpu *Cpu) ThumbPushPop(op uint16) {
	var (
		r     = &cpu.Reg.R
		pclr  = (op>>8)&1 != 0
		rlist = op & 0xFF
		pop   = (op>>11)&1 != 0
		p     unsafe.Pointer
	)

	reg := 0
	if !pop {
		reg = 7
	}

	// disabled for now. Need method to handle games that use edge of bank to subtract from. ex. metroid uses 0x200_0000 as addr, then subtracts to place values in different bank at 0x1FF_FFFC
	//if pop {
	//	p, _ = cpu.Mem.ReadPtr(r[SP])
	//} else {
	//	p, _ = cpu.Mem.WritePtr(r[SP])
	//}

	if !pop && pclr {
		r[SP] -= 4
		if p != nil {
			p = unsafe.Add(p, -4)
			*(*uint32)(p) = r[14]
		} else {
			cpu.Mem.Write32(r[SP], r[14])
		}
	}

	for range 8 {
		if disabled := (rlist>>reg)&1 == 0; disabled {
			if pop {
				reg++
			} else {
				reg--
			}
			continue
		}

		if pop {
			if p != nil {
				r[reg] = *(*uint32)(p)
				p = unsafe.Add(p, 4)
			} else {
				r[reg] = cpu.Mem.Read32(r[SP])
			}
			r[SP] += 4
		} else {
			r[SP] -= 4
			if p != nil {
				p = unsafe.Add(p, -4)
				*(*uint32)(p) = r[reg]
			} else {
				cpu.Mem.Write32(r[SP], r[reg])
			}
		}

		if pop {
			reg++
		} else {
			reg--
		}
	}

	if pop && pclr {

		if p != nil {
			r[PC] = *(*uint32)(p)
		} else {
			r[PC] = cpu.Mem.Read32(r[SP])
		}

		cpu.ToggleThumb()

		r[SP] += 4
		return
	}

	r[PC] += 2
}
