// Code generated by '_gen'
package arm9

import (
	amd64 "github.com/aabalke/gojit"
)

func (j *Jit) EmitThumbSdt(op uint32) {
	var (
		inst = (op >> 10) & 0b11
		rd   = op & 0x7
	)

	j.Movl(j.REG((op>>3)&0x7), amd64.Eax)
	j.Add(j.REG((op>>6)&0x7), amd64.Eax)

	if signed := (op>>9)&1 != 0; signed {

		switch inst {
		case THUMB_STRH:

			j.And(amd64.Imm(^1), amd64.Eax)
			j.Movl(j.REG(rd), amd64.Ebx)
			j.CallFunc(Write16)

		case THUMB_LDSB:

			// sign-expand byte value
			// r[rd] = uint32(int32(int8(cpu.mem.Read8(addr, false))))

			j.CallFunc(Read)
			j.Movsx(amd64.Al, amd64.Eax)
			j.Movl(amd64.Eax, j.REG(rd))

		case THUMB_LDRH:

			j.Movl(amd64.Eax, amd64.R8d)
			j.And(amd64.Imm(^1), amd64.Eax)
			j.CallFunc(Read16)

			j.Movl(amd64.R8d, amd64.Ecx)
			j.And(amd64.Imm(1), amd64.Ecx)
			j.Shl(amd64.Imm(3), amd64.Ecx)
			j.RorCl(amd64.Eax)

			j.Movl(amd64.Eax, j.REG(rd))

		case THUMB_LDSH:

			j.And(amd64.Imm(^1), amd64.Rax)
			j.CallFunc(Read16)
			j.Movsx(amd64.Ax, amd64.Rax)
			j.Movl(amd64.Eax, j.REG(rd))

		}
		return
	}

	switch inst {
	case THUMB_STR_REG:
		j.And(amd64.Imm(^0b11), amd64.Eax)
		j.Movl(j.REG(rd), amd64.Ebx)
		j.CallFunc(Write32)
	case THUMB_LDR_REG:

		j.Movl(amd64.Eax, amd64.R8d)
		j.And(amd64.Imm(^0b11), amd64.Eax)
		j.CallFunc(Read32)

		j.Movl(amd64.R8d, amd64.Ecx)
		j.And(amd64.Imm(0b11), amd64.Ecx)
		j.Shl(amd64.Imm(3), amd64.Ecx)
		j.RorCl(amd64.Eax)

		j.Movl(amd64.Eax, j.REG(rd))
	case THUMB_STRB_REG:
		j.Movl(j.REG(rd), amd64.Ebx)
		j.CallFunc(Write)
	case THUMB_LDRB_REG:
		j.CallFunc(Read)
		j.Movl(amd64.Eax, j.REG(rd))
	}
}
