// Code generated by '_gen'
package arm9

import (
	a "github.com/aabalke/gojit"
)

func (j *Jit) EmitThumbSdt(op uint16) {
	var (
		inst = (op >> 10) & 0b11
		rd   = uint32(op & 0x7)
	)

	j.LdrReg(a.R00, uint32(op>>3)&7)
	j.LdrReg(a.R01, uint32(op>>6)&7)
	j.ADDReg(a.R00, a.R00, a.R01, 0, 0, false, false, false)

	if signed := (op>>9)&1 != 0; signed {

		switch inst {
		case THUMB_STRH:
			j.LdrReg(a.R01, rd)
			j.AndImm(a.R00, a.R00, a.EncodeImm(0xFFFF_FFFE, false), false, false)
			j.CallFunc(Write16)

		case THUMB_LDSB:

			// sign-expand byte value
			j.CallFunc(Read)
			j.Sxtb(a.R00, a.R00, false)
			j.StrReg(a.R00, rd)

		case THUMB_LDRH:

			j.MovReg(a.R08, a.R00, false)
			j.AndImm(a.R00, a.R00, a.EncodeImm(0xFFFF_FFFE, false), false, false)

			j.CallFunc(Read16)

			j.MovReg(a.R01, a.R08, false)
			j.AndImm(a.R01, a.R01, IMM_1, false, false)
			j.LslImm(a.R01, a.R01, 3, false)
			j.RorReg(a.R00, a.R00, a.R01, false)
			j.StrReg(a.R00, rd)

		case THUMB_LDSH:

			// sign-expand half value
			j.AndImm(a.R00, a.R00, a.EncodeImm(0xFFFF_FFFE, false), false, false)
			j.CallFunc(Read16)
			j.Sxth(a.R00, a.R00, false)
			j.StrReg(a.R00, rd)

		}

		return
	}

	switch inst {
	case THUMB_STR_REG:
		j.LdrReg(a.R01, rd)
		j.AndImm(a.R00, a.R00, IMM_0xFFFF_FFFC, false, false)
		j.CallFunc(Write32)

	case THUMB_STRB_REG:
		j.LdrReg(a.R01, rd)
		j.CallFunc(Write)

	case THUMB_LDR_REG:
		j.MovReg(a.R08, a.R00, false)
		j.AndImm(a.R00, a.R00, IMM_0xFFFF_FFFC, false, false)

		j.CallFunc(Read32)

		j.MovReg(a.R01, a.R08, false)
		j.AndImm(a.R01, a.R01, IMM_3, false, false)
		j.LslImm(a.R01, a.R01, 3, false)
		j.RorReg(a.R00, a.R00, a.R01, false)
		j.StrReg(a.R00, rd)
	case THUMB_LDRB_REG:

		j.CallFunc(Read)
		j.StrReg(a.R00, rd)
	}
}
