// Code generated by '_gen'
package arm9

import (
	"fmt"
	"math/bits"

	"github.com/aabalke/guac/emu/gba/cpu"
)

func (c *Cpu) DecodeTHUMB(op uint16) {
	switch {
	case IsThumbBkpt(op):
		c.Exception(cpu.VEC_PREFETCH, cpu.MODE_ABT)
	case cpu.IsthumbSWI(op):
		c.Exception(cpu.VEC_SWI, cpu.MODE_SWI)
	case cpu.IsThumbAddSub(op):
		c.ThumbAddSub(op)
	case cpu.IsThumbShift(op):
		c.ThumbShifted(op)
	case cpu.IsThumbImm(op):
		c.ThumbImm(op)
	case cpu.IsThumbAlu(op):
		c.ThumbAlu(op)
	case cpu.IsThumbHiReg(op):
		c.HiRegBX(op)
	case cpu.IsLSHalf(op):
		c.ThumbLSHalf(op)
	case cpu.IsThumbSdt(op):
		c.ThumbSdt(op)
	case cpu.IsLPC(op):
		c.ThumbLPC(op)
	case cpu.IsLSImm(op):
		c.ThumbLSImm(op)
	case cpu.IsPushPop(op):
		c.ThumbPushPop(op)
	case cpu.IsRelative(op):
		c.ThumbRelative(op)
	case cpu.IsThumbB(op):
		c.ThumbB(op)
	case cpu.IsJumpCall(op):
		c.ThumbJumpCalls(op)
	case cpu.IsStack(op):
		c.ThumbStack(op)
	case cpu.IsLongBranch(op):
		c.ThumbLongBranch(op)
	case cpu.IsShortLongBranch(op):
		c.ThumbShortLongBranch(op)
	case IsThumbShortBlx(op):
		c.ThumbShortBlx(op)
	case cpu.IsLSSP(op):
		c.ThumbLSSP(op)
	case cpu.IsMulti(op):
		c.ThumbBlock(op)
	default:
		panic(fmt.Sprintf("nds: unable to decode arm9 thumb pc=%08X op=%08X", c.Reg.R[PC], op))
	}
}

//go:inline
func IsThumbBkpt(op uint16) bool {
	return cpu.IsThumbOpFormat(
		op,
		0b1011_1110_0000_0000,
		0b1111_1111_0000_0000,
	)
}

//go:inline
func IsThumbShortBlx(op uint16) bool {
	return cpu.IsThumbOpFormat(
		op,
		0b1111_1000_0000_0000,
		0b1110_1000_0000_0000,
	)
}

func (c *Cpu) ThumbShortBlx(op uint16) {
	r := &c.Reg.R

	nn := uint32(op&0x7FF) << 1
	tmp := (r[PC] - 2) | 1
	r[PC] = r[LR] + nn
	r[LR] = tmp

	c.ToggleThumb()
}

func (c *Cpu) ThumbSdt(op uint16) {
	var (
		r    = &c.Reg.R
		inst = (op >> 10) & 0b11
		rd   = op & 0x7
		addr = r[(op>>3)&0x7] + r[(op>>6)&0x7]
	)

	if signed := (op>>9)&1 != 0; signed {

		switch inst {
		case cpu.THUMB_STRH:
			c.Write16(addr, uint16(r[rd]))

		case cpu.THUMB_LDSB:
			// sign-expand byte value
			r[rd] = uint32(int32(int8(c.Read8(addr))))

		case cpu.THUMB_LDRH:
			v := c.Read16(addr)
			r[rd] = bits.RotateLeft32(v, -int((addr&1)<<3))

		case cpu.THUMB_LDSH:
			// On ARM9 aka NDS9 sign extend:
			r[rd] = uint32(int32(int16(c.Read16(addr))))
		}

		return
	}

	switch inst {
	case cpu.THUMB_STR_REG:
		c.Write32(addr, r[rd])
	case cpu.THUMB_STRB_REG:
		c.Write8(addr, uint8(r[rd]))
	case cpu.THUMB_LDR_REG:
		v := c.Read32(addr)
		is := (addr & 3) << 3
		r[rd] = bits.RotateLeft32(v, -int(is))
	case cpu.THUMB_LDRB_REG:
		r[rd] = c.Read8(addr)
	}
}

func (c *Cpu) ThumbPushPop(op uint16) {
	var (
		r     = &c.Reg.R
		pclr  = (op>>8)&1 != 0
		rlist = op & 0xFF
		pop   = (op>>11)&1 != 0
		seq   = uint32(cpu.NONSEQ)
	)

	// thank you nano
	if rlist == 0 && !pclr {
		if pop {
			r[PC] = c.Read32Block(r[SP], seq)
			c.Reload16()
			r[SP] += 0x40
		} else {
			// alyosha test fails this.
			// i think it is timing related
			r[SP] -= 0x40
			c.Write32Block(r[SP], r[PC], seq)
		}

		return
	}

	if pop {
		for reg := range 8 {
			if disabled := (rlist>>reg)&1 == 0; disabled {
				continue
			}

			r[reg] = c.Read32Block(r[SP], seq)
			r[SP] += 4

			seq = cpu.SEQ
		}

		if pclr {

			r[PC] = c.Read32Block(r[SP], seq)
			// arm9 toggle thumb switch based on bit 0, arm7 force aligned
			r[SP] += 4
			c.Idle(1)
			c.ToggleThumb()
			return
		}

		c.Idle(1)

	} else {

		if pclr {
			r[SP] -= 4
			c.Write32Block(r[SP], r[14], seq)
		}

		for reg := 7; reg >= 0; reg-- {
			if disabled := (rlist>>reg)&1 == 0; disabled {
				continue
			}

			r[SP] -= 4
			c.Write32Block(r[SP], r[reg], seq)

			seq = cpu.SEQ
		}
	}
}

func (c *Cpu) HiRegBX(op uint16) {
	if nop := op == 0x46C0; nop {
		return
	}

	var (
		r  = &c.Reg.R
		rd = (op & 7) | (((op >> 7) & 1) << 3)
		rs = (op >> 3) & 0xF
	)

	switch inst := (op >> 8) & 3; inst {
	case cpu.HI_ADD:

		r[rd] += r[rs]

		if rd == PC {
			c.Reload16()
		}

	case cpu.HI_CMP:

		rsv := r[rs]
		rdv := r[rd]
		res := uint64(rdv) - uint64(rsv)

		cpsr := &c.Reg.CPSR
		cpsr.N = (uint32(res)>>31)&1 != 0
		cpsr.Z = uint32(res) == 0
		cpsr.C = res < 0x1_0000_0000
		cpsr.V = ((rdv^rsv)&(rdv^uint32(res)))>>31 != 0

	case cpu.HI_MOV:

		r[rd] = r[rs]

		if rd == PC {
			c.Reload16()
		}

	case cpu.HI_BX:

		if blx := op&(1<<7) != 0; blx {

			// need tmp ret for blx LR (pc = old LR, lr = calc ret)
			ret := r[PC] - 1
			r[PC] = r[rs]
			r[LR] = ret
			c.ToggleThumb()
			return
		}

		r[PC] = r[rs]
		c.ToggleThumb()
	}
}
