// Code generated by '_gen'
package arm

import (
	"fmt"
	"strings"
	"unsafe"

	"github.com/aabalke/guac/emu/cpu"
)

type Waitstate interface {
	Get(width, addr uint32, seq bool) int64
}

type Prefetch interface {
	Cancel()
	Step(cycles int64)
	Wait(addr uint32, cycles int64, thumb bool) int64
	Restart(addr uint32, thumb bool)
}

type Cpu struct {
	P      Pipeline
	Reg    Reg
	Mem    cpu.MemoryInterface
	Irq    *cpu.Irq
	Halted bool

	PcPtr       unsafe.Pointer
	PcOff       int
	IsBranching bool
	BranchPc    uint32

	LowVector bool

	AccCycles     int
	NonSeq        bool
	BlockTransfer bool

	Waitstate Waitstate
	Prefetch  Prefetch
}

type Pipeline struct {
	Execute Inst
	Decode  Inst
	Fetch   Inst
	Reload  bool
}

type Inst struct {
	Addr  uint32
	Op    uint32
	Thumb bool
}

const (
	SP = 13
	LR = 14
	PC = 15

	FLAG_N = 31
	FLAG_Z = 30
	FLAG_C = 29
	FLAG_V = 28
	FLAG_Q = 27
	FLAG_I = 7
	FLAG_F = 6
	FLAG_T = 5

	MODE_USR = 0x10
	MODE_FIQ = 0x11
	MODE_IRQ = 0x12
	MODE_SWI = 0x13
	MODE_ABT = 0x17
	MODE_UND = 0x1B
	MODE_SYS = 0x1F
)

func (c *Cond) CheckCond(cond uint32) bool {
	switch cond {
	case 0xE: // AL (always)
		return true
	case 0x0: // EQ
		return c.Z
	case 0x1: // NE
		return !c.Z
	case 0x2: // CS/HS
		return c.C
	case 0x3: // CC/LO
		return !c.C
	case 0x4: // MI
		return c.N
	case 0x5: // PL
		return !c.N
	case 0x6: // VS
		return c.V
	case 0x7: // VC
		return !c.V
	case 0x8: // HI
		return c.C && !c.Z
	case 0x9: // LS
		return !c.C || c.Z
	case 0xA: // GE
		return c.N == c.V
	case 0xB: // LT
		return c.N != c.V
	case 0xC: // GT
		return !c.Z && (c.N == c.V)
	case 0xD: // LE
		return c.Z || (c.N != c.V)
	default: // NV
		return false
	}
}

var BANK_ID = map[uint32]uint32{
	MODE_USR: 0,
	MODE_SYS: 0,
	MODE_FIQ: 1,
	MODE_IRQ: 2,
	MODE_SWI: 3,
	MODE_ABT: 4,
	MODE_UND: 5,
}

func NewCpu(jitEnabled bool, m cpu.MemoryInterface, irq *cpu.Irq, ws Waitstate, prefetch Prefetch) *Cpu {
	c := &Cpu{
		Mem:       m,
		Irq:       irq,
		LowVector: true,
		Waitstate: ws,
		Prefetch:  prefetch,
	}

	// skip bios
	c.Irq.IME = true
	c.P.Reload = true
	c.NonSeq = true

	return c
}

func (c *Cpu) Step() int {
	c.AccCycles = 0

	if c.P.Reload {
		c.Reload()
	}

	c.Fetch()

	if c.Irq.IE&c.Irq.IF != 0 {
		c.Halted = false

		if !c.Reg.CPSR.I && c.Irq.IME {
			c.Exception(VEC_IRQ, MODE_IRQ)

			if c.P.Execute.Thumb {
				c.Reg.R[14] += 2
			}

			return c.AccCycles
		}
	}

	if c.P.Execute.Thumb {
		c.DecodeTHUMB(uint16(c.P.Execute.Op))
	} else {
		c.DecodeARM(c.P.Execute.Op)
	}

	return c.AccCycles
}

func (c *Cpu) Fetch() {
	c.P.Execute = c.P.Decode
	c.P.Decode = c.P.Fetch

	seq := !c.NonSeq
	c.NonSeq = false

	if c.Reg.CPSR.T {
		c.Reg.R[15] = (c.Reg.R[15] + 2) &^ 1
		c.P.Fetch.Op = c.InstRead16(c.Reg.R[15], seq)
	} else {
		c.Reg.R[15] = (c.Reg.R[15] + 4) &^ 3
		c.P.Fetch.Op = c.InstRead32(c.Reg.R[15], seq)
	}
	c.P.Fetch.Addr = c.Reg.R[15]
	c.P.Fetch.Thumb = c.Reg.CPSR.T
}

func (c *Cpu) Reload() {
	c.P.Reload = false

	thumb := c.Reg.CPSR.T
	if thumb {
		c.Reg.R[15] &^= 1
		c.P.Fetch.Op = c.InstRead16(c.Reg.R[15], false)
	} else {
		c.Reg.R[15] &^= 3
		c.P.Fetch.Op = c.InstRead32(c.Reg.R[15], false)
	}
	c.P.Fetch.Addr = c.Reg.R[15]
	c.P.Fetch.Thumb = thumb

	c.NonSeq = false

	c.Fetch()
}

func (p *Pipeline) String() string {
	var b strings.Builder

	//fmt.Fprintf(&b, "Fetch %08X %08X ", p.Fetch.Addr, p.Fetch.Op)
	//fmt.Fprintf(&b, "Decode %08X %08X ", p.Decode.Addr, p.Decode.Op)
	fmt.Fprintf(&b, "Execute %08X %08X ", p.Execute.Addr, p.Execute.Op)

	return b.String()
}

type Reg struct {
	R    [16]uint32
	SP   [6]uint32
	LR   [6]uint32
	FIQ  [5]uint32 // r8 - r12
	USR  [5]uint32 // r8 - r12 // tmp to restore after FIQ
	CPSR Cond
	SPSR [6]Cond
}

type Cond struct {
	N, Z, C, V, Q, I, F, T bool
	Mode                   uint32
}

//go:nosplit
func (c *Cond) Get() uint32 {
	v := c.Mode

	if c.N {
		v |= 1 << FLAG_N
	}
	if c.Z {
		v |= 1 << FLAG_Z
	}
	if c.C {
		v |= 1 << FLAG_C
	}
	if c.V {
		v |= 1 << FLAG_V
	}
	if c.Q {
		v |= 1 << FLAG_Q
	}
	if c.I {
		v |= 1 << FLAG_I
	}
	if c.F {
		v |= 1 << FLAG_F
	}
	if c.T {
		v |= 1 << FLAG_T
	}

	return v
}

func (c *Cond) Set(v uint32) {
	c.N = (v>>FLAG_N)&1 != 0
	c.Z = (v>>FLAG_Z)&1 != 0
	c.C = (v>>FLAG_C)&1 != 0
	c.V = (v>>FLAG_V)&1 != 0
	c.Q = (v>>FLAG_Q)&1 != 0
	c.I = (v>>FLAG_I)&1 != 0
	c.F = (v>>FLAG_F)&1 != 0
	c.T = (v>>FLAG_T)&1 != 0
	c.Mode = v & 0x1F
}

func (cpu *Cpu) ToggleThumb() {
	r := &cpu.Reg.R
	cpsr := &cpu.Reg.CPSR

	cpsr.T = r[PC]&1 != 0

	if cpsr.T {
		r[PC] &^= 1
		return
	}

	r[PC] &^= 3
}

func (c *Cpu) Write8(addr uint32, v uint8) {
	c.Mem.Write8(addr, v)
	c.AccCycles += c.CycleCounter(addr, 1, false, false)
	c.NonSeq = true
}

func (c *Cpu) Write16(addr uint32, v uint16) {
	c.Mem.Write16(addr, v)
	c.AccCycles += c.CycleCounter(addr, 2, false, false)
	c.NonSeq = true
}

func (c *Cpu) Write32(addr uint32, v uint32) {
	c.Mem.Write32(addr, v)
	c.AccCycles += c.CycleCounter(addr, 4, c.BlockTransfer, false)
	c.NonSeq = true
}

func (c *Cpu) Read8(addr uint32) uint32 {
	c.AccCycles += c.CycleCounter(addr, 1, false, false)
	c.idle(1)
	return c.Mem.Read8(addr)
}

func (c *Cpu) Read16(addr uint32) uint32 {
	c.AccCycles += c.CycleCounter(addr, 2, false, false)
	c.idle(1)
	return c.Mem.Read16(addr)
}

func (c *Cpu) Read32(addr uint32) uint32 {
	c.AccCycles += c.CycleCounter(addr, 4, c.BlockTransfer, false)

	if !c.BlockTransfer {
		c.idle(1)
	}
	return c.Mem.Read32(addr)
}

func (c *Cpu) InstRead16(addr uint32, seq bool) uint32 {
	c.AccCycles += c.CycleCounter(addr, 2, seq, true)
	return c.Mem.Read16(addr)
}

func (c *Cpu) InstRead32(addr uint32, seq bool) uint32 {
	c.AccCycles += c.CycleCounter(addr, 4, seq, true)
	return c.Mem.Read32(addr)
}

func (c *Cpu) CycleCounter(addr, width uint32, seq, inst bool) int {
	prefetch := true

	cycles := 1

	switch addr >> 24 {
	case 2:
		cycles = 3 << (width >> 2)
	case 5, 6:
		cycles = 1 << (width >> 2)
	case 8, 9, 10, 11, 12, 13:

		if addr&0x1FFFF == 0 {
			seq = false
		}

		cycles = int(c.Waitstate.Get(width, addr, seq))
		prefetch = false
		if inst {
			cycles = int(c.Prefetch.Wait(addr, int64(cycles), c.Reg.CPSR.T))
		} else {
			c.Prefetch.Cancel()
		}

	case 14, 15:

		c.Prefetch.Cancel()
		cycles = int(c.Waitstate.Get(width, addr, seq))
		prefetch = false
	}

	if prefetch {
		c.Prefetch.Step(int64(cycles))
	}

	return cycles
}

func idleMul(rs uint32, sign bool) int {
	cycles := 1
	mask := uint32(0xFFFFFF00)
	for {
		rs &= mask
		if rs == 0 {
			break
		}
		if sign && (rs == mask) {
			break
		}
		mask <<= 8
		cycles++
	}
	return cycles
}

func (c *Cpu) idle(cycles int) {
	c.AccCycles += cycles
	c.NonSeq = true
	c.Prefetch.Step(int64(cycles))
}
