// Code generated by '_gen'
package arm

const (
	VEC_RESET         = 0xFFFF_0000
	VEC_UND           = 0xFFFF_0004
	VEC_SWI           = 0xFFFF_0008
	VEC_PREFETCHABORT = 0xFFFF_000C
	VEC_DATAABORT     = 0xFFFF_0010
	VEC_ADDR26BIT     = 0xFFFF_0014
	VEC_IRQ           = 0xFFFF_0018
	VEC_FIQ           = 0xFFFF_001C
)

func (cpu *Cpu) Exception(addr uint32, mode uint32) {
	var (
		cpsr = &cpu.Reg.CPSR
		reg  = &cpu.Reg
		r    = &cpu.Reg.R
	)

	cpu.ModeSwitch(cpsr.Mode, mode)

	i := BANK_ID[mode]
	reg.SPSR[i] = *cpsr

	r[LR] = cpu.P.Decode.Addr
	reg.LR[i] = cpu.P.Decode.Addr

	cpsr.Mode = mode
	cpsr.T = false
	cpsr.I = true
	if mode == MODE_FIQ {
		cpsr.F = true
	}

	cpu.P.Reload = true

	if cpu.LowVector {
		r[PC] = addr & 0xFFFF
	} else {
		r[PC] = addr
	}
}

func (cpu *Cpu) ExitException(mode uint32) {
	var (
		cpsr = &cpu.Reg.CPSR
		reg  = &cpu.Reg
	)

	*cpsr = reg.SPSR[BANK_ID[mode]]

	cpu.ModeSwitch(mode, cpsr.Mode)
}
