// Code generated by '_gen'
package arm

const (
	VEC_RESET         = 0xFFFF_0000
	VEC_UND           = 0xFFFF_0004
	VEC_SWI           = 0xFFFF_0008
	VEC_PREFETCHABORT = 0xFFFF_000C
	VEC_DATAABORT     = 0xFFFF_0010
	VEC_ADDR26BIT     = 0xFFFF_0014
	VEC_IRQ           = 0xFFFF_0018
	VEC_FIQ           = 0xFFFF_001C
)

func (c *Cpu) Exception(addr uint32, mode uint32) {
	var (
		cpsr = &c.Reg.CPSR
		reg  = &c.Reg
		r    = &c.Reg.R
	)

	c.ModeSwitch(cpsr.Mode, mode)

	i := BANK_ID[mode]
	reg.SPSR[i] = *cpsr

	r[LR] = c.P.Decode.Addr
	reg.LR[i] = c.P.Decode.Addr

	cpsr.Mode = mode
	cpsr.T = false
	cpsr.I = true
	if mode == MODE_FIQ {
		cpsr.F = true
	}

	c.P.Reload = true

	if c.LowVector {
		r[PC] = addr & 0xFFFF
	} else {
		r[PC] = addr
	}
}

func (c *Cpu) ExitException(mode uint32) {
	var (
		cpsr = &c.Reg.CPSR
		reg  = &c.Reg
	)

	*cpsr = reg.SPSR[BANK_ID[mode]]

	c.ModeSwitch(mode, cpsr.Mode)
}
