// Code generated by '_gen'
package arm

import (
	"fmt"
)

func (c *Cpu) DecodeTHUMB(op uint16) {
	switch {
	case IsthumbSWI(op):
		c.Exception(VEC_SWI, MODE_SWI)
	case IsThumbAddSub(op):
		c.ThumbAddSub(op)
	case IsThumbShift(op):
		c.ThumbShifted(op)
	case IsThumbImm(op):
		c.ThumbImm(op)
	case IsThumbAlu(op):
		c.ThumbAlu(op)
	case IsThumbHiReg(op):
		c.HiRegBX(op)
	case IsLSHalf(op):
		c.ThumbLSHalf(op)
	case IsThumbSdt(op):
		c.ThumbSdt(op)
	case IsLPC(op):
		c.ThumbLPC(op)
	case IsLSImm(op):
		c.ThumbLSImm(op)
	case IsPushPop(op):
		c.ThumbPushPop(op)
	case IsRelative(op):
		c.ThumbRelative(op)
	case IsThumbB(op):
		c.ThumbB(op)
	case IsJumpCall(op):
		c.ThumbJumpCalls(op)
	case IsStack(op):
		c.ThumbStack(op)
	case IsLongBranch(op):
		c.ThumbLongBranch(op)
	case IsShortLongBranch(op):
		c.ThumbShortLongBranch(op)
	case IsLSSP(op):
		c.ThumbLSSP(op)
	case IsMulti(op):
		c.ThumbBlock(op)
	default:
		r := &c.Reg.R
		panic(fmt.Sprintf("Unable to Decode ARM false %04X, at PC %08X\n", op, r[PC]))
	}
}

//go:inline
func IsThumbOpFormat(op, mask, fmt uint16) bool {
	return op&mask == fmt
}

//go:inline
func IsThumbShift(op uint16) bool {
	return IsThumbOpFormat(
		op,
		0b1110_0000_0000_0000,
		0b0000_0000_0000_0000,
	)
}

//go:inline
func IsThumbAddSub(op uint16) bool {
	return IsThumbOpFormat(
		op,
		0b1111_1000_0000_0000,
		0b0001_1000_0000_0000,
	)
}

//go:inline
func IsThumbImm(op uint16) bool {
	return IsThumbOpFormat(
		op,
		0b1110_0000_0000_0000,
		0b0010_0000_0000_0000,
	)
}

//go:inline
func IsThumbAlu(op uint16) bool {
	return IsThumbOpFormat(
		op,
		0b1111_1100_0000_0000,
		0b0100_0000_0000_0000,
	)
}

//go:inline
func IsThumbHiReg(op uint16) bool {
	return IsThumbOpFormat(
		op,
		0b1111_1100_0000_0000,
		0b0100_0100_0000_0000,
	)
}

//go:inline
func IsLSHalf(op uint16) bool {
	return IsThumbOpFormat(
		op,
		0b1111_0000_0000_0000,
		0b1000_0000_0000_0000,
	)
}

//go:inline
func IsThumbSdt(op uint16) bool {
	return IsThumbOpFormat(
		op,
		0b1111_0000_0000_0000,
		0b0101_0000_0000_0000,
	)
}

//go:inline
func IsLPC(op uint16) bool {
	return IsThumbOpFormat(
		op,
		0b1111_1000_0000_0000,
		0b0100_1000_0000_0000,
	)
}

//go:inline
func IsLSImm(op uint16) bool {
	return IsThumbOpFormat(
		op,
		0b1110_0000_0000_0000,
		0b0110_0000_0000_0000,
	)
}

//go:inline
func IsPushPop(op uint16) bool {
	return IsThumbOpFormat(
		op,
		0b1111_0110_0000_0000,
		0b1011_0100_0000_0000,
	)
}

//go:inline
func IsRelative(op uint16) bool {
	return IsThumbOpFormat(
		op,
		0b1111_0000_0000_0000,
		0b1010_0000_0000_0000,
	)
}

//go:inline
func IsJumpCall(op uint16) bool {
	return IsThumbOpFormat(
		op,
		0b1111_0000_0000_0000,
		0b1101_0000_0000_0000,
	)
}

//go:inline
func IsThumbB(op uint16) bool {
	return IsThumbOpFormat(
		op,
		0b1111_1000_0000_0000,
		0b1110_0000_0000_0000,
	)
}

//go:inline
func IsStack(op uint16) bool {
	return IsThumbOpFormat(
		op,
		0b1111_1111_0000_0000,
		0b1011_0000_0000_0000,
	)
}

//go:inline
func IsLongBranch(op uint16) bool {
	return IsThumbOpFormat(
		op,
		0b1111_1000_0000_0000,
		0b1111_0000_0000_0000,
	)
}

//go:inline
func IsShortLongBranch(op uint16) bool {
	return IsThumbOpFormat(
		op,
		0b1111_1000_0000_0000,
		0b1111_1000_0000_0000,
	)
}

//go:inline
func IsLSSP(op uint16) bool {
	return IsThumbOpFormat(
		op,
		0b1111_0000_0000_0000,
		0b1001_0000_0000_0000,
	)
}

//go:inline
func IsMulti(op uint16) bool {
	return IsThumbOpFormat(
		op,
		0b1111_0000_0000_0000,
		0b1100_0000_0000_0000,
	)
}

//go:inline
func IsthumbSWI(op uint16) bool {
	return IsThumbOpFormat(
		op,
		0b1111_1111_0000_0000,
		0b1101_1111_0000_0000,
	)
}
