# keyboard ids come from ebitengine string values.

# gamepad / controller ids: https://www.w3.org/TR/gamepad/#remapping

# only cancel audio init for profiling / benchmarking
#cancel_audio_init = true

#fullscreen = true
backdrop_color = 0x0A0A0A

# Define how many games appear per row on game select screen
games_per_row = 6

[keyboard]
select = ["J", "Enter"]
mute = ["M"]
pause = ["P"]
quit = ["Q"]
fullscreen = ["F11"]
left = ["A", "ArrowLeft"]
right = ["D", "ArrowRight"]
up = ["W", "ArrowUp"]
down = ["S", "ArrowDown"]

[controller]
select = [1]
mute = [8]
pause = [9]
left = [14]
right = [15]
up = [12]
down = [13]

# GB Configuration

[gb]
# Define a 4 color palette to replace greyscale using hex values
# From lightest -> darkest
# if invalid input, will fall back to greyscale
# dmg_palette = [ 0xE0F8D0, 0x88C070, 0x346856, 0x081820 ]

[gb.keyboard]

a = ["J"]
b = ["K"]
select = ["L"]
start = ["Semicolon"]
left = ["A"]
right = ["D"]
up = ["W"]
down = ["S"]

[gb.controller]
a = [1]
b = [0]
select = [2]
start = [3]
left = [14]
right = [15]
up = [12]
down = [13]

# GBA Configuration

[gba]

# Experimental options which may cause crashes or glitches
# skip_hle = true 
#threads = 8
idle_optimize = true

# set between 1 - 1232 to set how often the sound clock is updated
# lower is more often, which is great for quality
# higher is better for lower end systems that cannot render sound fast enough
sound_clock_update_cycles = 0x200

[gba.keyboard]
a = ["J"]
b = ["K"]
select = ["L"]
start = ["Semicolon"]
left = ["A"]
right = ["D"]
up = ["W"]
down = ["S"]
r = ["Y"]
l = ["T"]

[gba.controller]
a = [1]
b = [0]
select = [2]
start = [3]
left = [14]
right = [15]
up = [12]
down = [13]
r = [5]
l = [4]
